// Clinic Audit Form schema — clinic performance, facilities, pricing (15–20 min)

export type ClinicAuditAnswers = Record<string, string | number | string[] | boolean | null>;
import {
  SUBMISSION_TYPE_OPTIONS,
  AUDIT_DEPTH_TYPE_OPTIONS,
  REQUESTED_BY_OPTIONS,
  REVIEW_PURPOSE_OPTIONS,
  COUNTRY_JURISDICTION_OPTIONS,
  BOOLEAN_YES_NO_OPTIONS,
  ADDITIONAL_OPERATOR_OPTIONS,
  PROCEDURE_TYPE_OPTIONS,
  AREAS_TREATED_OPTIONS,
  PATIENT_AGE_BRACKET_OPTIONS,
  PATIENT_SEX_OPTIONS,
  ETHNICITY_HAIR_BACKGROUND_OPTIONS,
  HAIR_TYPE_CURL_PATTERN_OPTIONS,
  HAIR_CALIBRE_CATEGORY_OPTIONS,
  HAIR_COLOUR_OPTIONS,
  SKIN_HAIR_CONTRAST_OPTIONS,
  PRIMARY_DIAGNOSIS_OPTIONS,
  SECONDARY_DIAGNOSIS_OPTIONS,
  HAIR_LOSS_SCALE_OPTIONS,
  HAIR_LOSS_STABILITY_OPTIONS,
  MINIATURISATION_REGION_OPTIONS,
  SCALP_CONDITION_FLAG_OPTIONS,
  ZONES_PLANNED_OPTIONS,
  CANDIDATE_SUITABILITY_OPTIONS,
  DONOR_QUALITY_RATING_OPTIONS,
  DONOR_DENSITY_RATING_OPTIONS,
  ESTIMATED_DONOR_CAPACITY_OPTIONS,
  OVERHARVESTING_SIGN_OPTIONS,
  EXTRACTION_DEVICE_OPTIONS,
  PUNCH_SIZE_OPTIONS,
  PUNCH_TYPE_OPTIONS,
  PUNCH_MANUFACTURER_OPTIONS,
  HOLDING_SOLUTION_OPTIONS,
  IMPLANTATION_DEVICE_OPTIONS,
  IMPLANTATION_METHOD_OPTIONS,
  IMPLANTED_BY_OPTIONS,
  IMPLANT_DEPTH_CONSISTENCY_OPTIONS,
  INTRAOP_ADJUNCT_OPTIONS,
  EXOSOME_TYPE_OPTIONS,
  POSTOP_TREATMENT_OPTIONS,
  OUTCOME_AUDIT_STAGE_OPTIONS,
  GROWTH_OUTCOME_CATEGORY_OPTIONS,
  DONOR_HEALING_CATEGORY_OPTIONS,
  PATIENT_SATISFACTION_CATEGORY_OPTIONS,
  REVIEW_CONCERN_CATEGORY_OPTIONS,
  CASE_COMPLEXITY_RATING_OPTIONS,
  AUDITOR_CONFIDENCE_LEVEL_OPTIONS,
  GRAFT_TRAY_QUALITY_RATING_OPTIONS,
  GRAFT_SORTING_METHOD_OPTIONS,
  VISIBLE_TRANSECTION_ON_TRAY_OPTIONS,
  GRAFT_TISSUE_QUALITY_CONCERN_OPTIONS,
  EXTRACTION_METHOD_OPTIONS,
  EXTRACTION_TECHNIQUE_OPTIONS,
  EXTRACTION_OPERATOR_OPTIONS,
  TRANSECTION_CATEGORY_OPTIONS,
  RECIPIENT_SITES_CREATED_BY_OPTIONS,
  SITE_CREATION_METHOD_OPTIONS,
  SLIT_ORIENTATION_OPTIONS,
  SITE_INSTRUMENT_SIZE_OPTIONS,
  HAIRLINE_DIRECTION_QUALITY_OPTIONS,
  OUT_OF_BODY_TIME_CATEGORY_OPTIONS,
  PUNCH_MOTION_OPTIONS,
  TEMPERATURE_CONTROLLED_STORAGE_OPTIONS,
} from "./audit/masterSurgicalMetadata";
import { clinicDefaultFields } from "@/config/auditSchema";

const CLINIC_AUDIT_SECTIONS_BASE = [
  {
    id: "clinic_info",
    title: "Clinic Information",
    questions: [
      { id: "clinic_name", prompt: "Clinic Name", type: "text", placeholder: "ABC Hair Clinic", required: true },
      { id: "clinic_location", prompt: "Clinic Location(s)", type: "text", placeholder: "Istanbul, Turkey; Dubai, UAE", required: true },
      { id: "phone", prompt: "Phone Number", type: "text", placeholder: "+90 123 456 7890", required: false },
      { id: "email", prompt: "Email Address", type: "text", placeholder: "info@abchairclinic.com", required: false },
      { id: "website", prompt: "Website", type: "text", placeholder: "www.abchairclinic.com", required: false },
      { id: "years_operation", prompt: "Years in Operation", type: "number", required: true },
    ],
  },
  {
    id: "facilities",
    title: "Clinic Facilities",
    questions: [
      { id: "operating_rooms", prompt: "Number of Operating Rooms", type: "number", required: true },
      { id: "recovery_areas", prompt: "Recovery Areas", type: "text", placeholder: "3 private recovery rooms", required: false },
      { id: "waiting_rooms", prompt: "Waiting Rooms", type: "text", placeholder: "2 waiting areas with refreshments", required: false },
      { id: "sterilization", prompt: "Sterilization and Hygiene Protocols", type: "text", placeholder: "Autoclave sterilization, daily deep cleaning", required: false },
      {
        id: "emergency_equipment",
        prompt: "Emergency Equipment",
        type: "checkbox",
        options: [
          { value: "defibrillator", label: "Defibrillator" },
          { value: "oxygen", label: "Oxygen Supply" },
          { value: "emergency_meds", label: "Emergency Medications" },
          { value: "backup_power", label: "Backup Power Supply" },
          { value: "other", label: "Other" },
        ],
        required: false,
      },
    ],
  },
  {
    id: "case_identity_submission_context",
    title: "Case Identity & Submission Context",
    questions: [
      {
        id: "submission_type",
        prompt: "Audit Submission Type",
        type: "select",
        options: SUBMISSION_TYPE_OPTIONS,
        required: true,
      },
      {
        id: "audit_type",
        prompt: "Audit Type",
        type: "select",
        options: AUDIT_DEPTH_TYPE_OPTIONS,
        required: true,
      },
      { id: "case_id", prompt: "Case ID", type: "text", required: true },
      { id: "clinic_name", prompt: "Clinic Name", type: "text", required: true },
      { id: "clinic_branch", prompt: "Clinic Branch / Location", type: "text", required: false },
      { id: "doctor_name", prompt: "Doctor Name", type: "text", required: true },
      {
        id: "country_jurisdiction",
        prompt: "Country / Jurisdiction",
        type: "select",
        options: COUNTRY_JURISDICTION_OPTIONS,
        required: true,
      },
      { id: "surgery_date", prompt: "Surgery Date", type: "date", required: true },
      {
        id: "multi_day_flag",
        prompt: "Multi-Day Procedure",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: true,
      },
      {
        id: "requested_by",
        prompt: "Requested By",
        type: "select",
        options: REQUESTED_BY_OPTIONS,
        required: true,
      },
      {
        id: "review_purpose",
        prompt: "Review Purpose",
        type: "checkbox",
        options: REVIEW_PURPOSE_OPTIONS,
        required: true,
      },
      {
        id: "previous_surgery_history",
        prompt: "Previous Surgery History",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: true,
      },
      {
        id: "repair_case_flag",
        prompt: "Corrective / Repair Case",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: true,
      },
    ],
  },
  {
    id: "case_identity_submission_context_advanced",
    title: "Advanced / Forensic Case Context",
    questions: [
      {
        id: "additional_operators",
        prompt: "Additional Surgeons / Operators",
        type: "checkbox",
        options: ADDITIONAL_OPERATOR_OPTIONS,
        required: false,
      },
      {
        id: "additional_operators_details",
        prompt: "Additional Operators (Names / Roles)",
        type: "textarea",
        required: false,
      },
      {
        id: "procedure_day_breakdown",
        prompt: "Procedure Day Breakdown",
        type: "textarea",
        required: false,
        dependsOn: { questionId: "multi_day_flag", value: "yes" },
      },
      {
        id: "previous_surgery_details",
        prompt: "Previous Surgery Details",
        type: "textarea",
        required: false,
        dependsOn: { questionId: "previous_surgery_history", value: "yes" },
      },
    ],
  },
  {
    id: "procedure_type_areas_treated_basic",
    title: "Basic Audit Questions — Procedure Type & Areas Treated",
    questions: [
      {
        id: "procedure_type",
        prompt: "Procedure Type",
        type: "checkbox",
        options: PROCEDURE_TYPE_OPTIONS,
        required: true,
      },
      {
        id: "primary_procedure_type",
        prompt: "Primary Procedure Type",
        type: "select",
        options: PROCEDURE_TYPE_OPTIONS,
        required: true,
      },
      {
        id: "areas_treated",
        prompt: "Areas Treated",
        type: "checkbox",
        options: AREAS_TREATED_OPTIONS,
        required: true,
      },
      {
        id: "primary_area_treated",
        prompt: "Primary Area Treated",
        type: "select",
        options: AREAS_TREATED_OPTIONS,
        required: false,
      },
      {
        id: "hairline_lowering_flag",
        prompt: "Hairline Lowering Performed",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: false,
      },
      {
        id: "crown_included_flag",
        prompt: "Crown Work Included",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: false,
      },
    ],
  },
  {
    id: "procedure_type_areas_treated_advanced",
    title: "Advanced / Forensic Questions — Procedure Type & Areas Treated",
    questions: [
      {
        id: "beard_donor_used",
        prompt: "Beard Donor Used",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: false,
      },
      {
        id: "body_donor_used",
        prompt: "Body Donor Used",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: false,
      },
    ],
  },
  {
    id: "patient_baseline_basic",
    title: "Basic Audit Questions — Patient Baseline",
    questions: [
      {
        id: "patient_age_bracket",
        prompt: "Patient Age Bracket",
        type: "select",
        options: PATIENT_AGE_BRACKET_OPTIONS,
        required: true,
      },
      {
        id: "patient_sex",
        prompt: "Sex",
        type: "select",
        options: PATIENT_SEX_OPTIONS,
        required: true,
      },
      {
        id: "ethnicity_hair_background",
        prompt: "Ethnicity / Hair Background",
        type: "checkbox",
        options: ETHNICITY_HAIR_BACKGROUND_OPTIONS,
        required: false,
      },
      {
        id: "hair_type_curl_pattern",
        prompt: "Hair Type / Curl Pattern",
        type: "select",
        options: HAIR_TYPE_CURL_PATTERN_OPTIONS,
        required: true,
      },
      {
        id: "hair_calibre_category",
        prompt: "Hair Calibre Category",
        type: "select",
        options: HAIR_CALIBRE_CATEGORY_OPTIONS,
        required: true,
      },
    ],
  },
  {
    id: "patient_baseline_advanced",
    title: "Advanced / Forensic Questions — Patient Baseline",
    questions: [
      {
        id: "hair_shaft_diameter_microns",
        prompt: "Exact Hair Shaft Diameter (microns)",
        type: "number",
        required: false,
      },
      {
        id: "hair_colour",
        prompt: "Hair Colour",
        type: "select",
        options: HAIR_COLOUR_OPTIONS,
        required: false,
      },
      {
        id: "skin_hair_contrast",
        prompt: "Skin / Hair Contrast",
        type: "select",
        options: SKIN_HAIR_CONTRAST_OPTIONS,
        required: false,
      },
    ],
  },
  {
    id: "diagnosis_pattern_basic",
    title: "Basic Audit Questions — Diagnosis & Hair Loss Pattern",
    questions: [
      {
        id: "primary_diagnosis",
        prompt: "Primary Diagnosis",
        type: "select",
        options: PRIMARY_DIAGNOSIS_OPTIONS,
        required: true,
      },
      {
        id: "hair_loss_scale_used",
        prompt: "Hair Loss Scale Used",
        type: "select",
        options: HAIR_LOSS_SCALE_OPTIONS,
        required: true,
      },
      {
        id: "hair_loss_grade",
        prompt: "Hair Loss Grade",
        type: "text",
        required: true,
        placeholder: "Grade / stage",
      },
      {
        id: "hair_loss_stability",
        prompt: "Hair Loss Stability",
        type: "select",
        options: HAIR_LOSS_STABILITY_OPTIONS,
        required: true,
      },
      {
        id: "miniaturisation_present",
        prompt: "Miniaturisation Present",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: true,
      },
    ],
  },
  {
    id: "diagnosis_pattern_advanced",
    title: "Advanced / Forensic Questions — Diagnosis & Hair Loss Pattern",
    questions: [
      {
        id: "secondary_diagnosis",
        prompt: "Secondary Diagnosis / Contributors",
        type: "checkbox",
        options: SECONDARY_DIAGNOSIS_OPTIONS,
        required: false,
      },
      {
        id: "miniaturisation_regions",
        prompt: "Miniaturisation Regions",
        type: "checkbox",
        options: MINIATURISATION_REGION_OPTIONS,
        required: false,
      },
      {
        id: "dupa_retrograde_flag",
        prompt: "DUPA / Retrograde Concern",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: false,
      },
      {
        id: "scalp_condition_flags",
        prompt: "Scalp Condition Flags",
        type: "checkbox",
        options: SCALP_CONDITION_FLAG_OPTIONS,
        required: false,
      },
    ],
  },
  {
    id: "preoperative_planning_basic",
    title: "Basic Audit Questions — Pre-Operative Planning",
    questions: [
      {
        id: "planned_graft_count",
        prompt: "Planned Graft Count",
        type: "number",
        required: true,
      },
      {
        id: "actual_graft_count",
        prompt: "Actual Graft Count",
        type: "number",
        required: true,
      },
      {
        id: "zones_planned",
        prompt: "Zones Planned",
        type: "checkbox",
        options: ZONES_PLANNED_OPTIONS,
        required: true,
      },
      {
        id: "future_loss_planning",
        prompt: "Future Loss Planning Considered",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: false,
      },
    ],
  },
  {
    id: "preoperative_planning_advanced",
    title: "Advanced / Forensic Questions — Pre-Operative Planning",
    questions: [
      {
        id: "estimated_hair_count",
        prompt: "Estimated Hair Count",
        type: "number",
        required: false,
      },
      {
        id: "density_goal_by_zone",
        prompt: "Density Goal by Zone",
        type: "textarea",
        required: false,
      },
      {
        id: "hairline_design_strategy",
        prompt: "Hairline Design Strategy",
        type: "textarea",
        required: false,
      },
      {
        id: "risk_counselling_documented",
        prompt: "Risk Counselling Documented",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: false,
      },
      {
        id: "candidate_suitability_rating",
        prompt: "Candidate Suitability Rating",
        type: "select",
        options: CANDIDATE_SUITABILITY_OPTIONS,
        required: false,
      },
    ],
  },
  {
    id: "donor_assessment_basic",
    title: "Basic Audit Questions — Donor Assessment",
    questions: [
      {
        id: "donor_quality_rating",
        prompt: "Donor Quality Rating",
        type: "select",
        options: DONOR_QUALITY_RATING_OPTIONS,
        required: true,
      },
      {
        id: "donor_density_rating",
        prompt: "Donor Density Rating",
        type: "select",
        options: DONOR_DENSITY_RATING_OPTIONS,
        required: true,
      },
      {
        id: "estimated_donor_capacity",
        prompt: "Estimated Donor Capacity",
        type: "select",
        options: ESTIMATED_DONOR_CAPACITY_OPTIONS,
        required: false,
      },
      {
        id: "estimated_donor_capacity_numeric",
        prompt: "Estimated Donor Capacity (numeric)",
        type: "number",
        required: false,
      },
      {
        id: "safe_donor_zone_assessed",
        prompt: "Safe Donor Zone Assessed",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: true,
      },
      {
        id: "donor_scarring_present",
        prompt: "Scarring Present in Donor",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: false,
      },
      {
        id: "overharvesting_risk_flag",
        prompt: "Overharvesting Risk Flag",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: false,
      },
    ],
  },
  {
    id: "donor_assessment_advanced",
    title: "Advanced / Forensic Questions — Donor Assessment",
    questions: [
      {
        id: "donor_density_per_cm2",
        prompt: "Donor Density per cm²",
        type: "number",
        required: false,
      },
      {
        id: "avg_hairs_per_graft",
        prompt: "Average Hairs per Graft",
        type: "number",
        required: false,
      },
      {
        id: "overharvesting_signs",
        prompt: "Overharvesting Signs Observed",
        type: "checkbox",
        options: OVERHARVESTING_SIGN_OPTIONS,
        required: false,
      },
      {
        id: "donor_mapping_notes",
        prompt: "Donor Mapping Notes",
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "staff",
    title: "Staff Qualifications",
    questions: [
      { id: "num_surgeons", prompt: "Number of Surgeons", type: "number", required: true },
      { id: "avg_experience", prompt: "Average Years of Experience for Surgeons", type: "number", required: false },
      { id: "num_nurses_techs", prompt: "Number of Nurses/Technicians", type: "number", required: false },
      { id: "staff_training", prompt: "Staff Training Programs", type: "text", placeholder: "Quarterly training on new techniques", required: false },
      { id: "staff_certifications", prompt: "Certifications of Key Staff", type: "text", placeholder: "All surgeons are ISHRS-certified", required: false },
    ],
  },
  {
    id: "statistics",
    title: "Procedure Statistics",
    questions: [
      { id: "procedures_annually", prompt: "Total Hair Transplant Procedures Performed Annually", type: "number", required: true },
      { id: "success_rate", prompt: "Success Rate (%)", type: "number", required: false },
      { id: "patient_satisfaction", prompt: "Patient Satisfaction Score", type: "rating", min: 1, max: 5, required: false },
      { id: "complication_rate", prompt: "Complication Rate (%)", type: "number", required: false },
    ],
  },
  {
    id: "surgical_metadata_basic",
    title: "Basic Audit Questions — Surgical Metadata",
    questions: [
      {
        id: "extraction_method",
        prompt: "Extraction Method",
        type: "checkbox",
        options: EXTRACTION_METHOD_OPTIONS,
        required: true,
      },
      {
        id: "extraction_devices_used",
        prompt: "Extraction Devices/Systems Used",
        type: "checkbox",
        options: EXTRACTION_DEVICE_OPTIONS,
        required: true,
      },
      {
        id: "extraction_technique",
        prompt: "Extraction Technique",
        type: "checkbox",
        options: EXTRACTION_TECHNIQUE_OPTIONS,
        required: true,
      },
      {
        id: "extraction_operator",
        prompt: "Extraction Performed By",
        type: "select",
        options: EXTRACTION_OPERATOR_OPTIONS,
        required: true,
      },
      {
        id: "punch_sizes_used",
        prompt: "Punch Sizes Used",
        type: "checkbox",
        options: PUNCH_SIZE_OPTIONS,
        required: true,
      },
      {
        id: "punch_types_used",
        prompt: "Punch Types Used",
        type: "checkbox",
        options: PUNCH_TYPE_OPTIONS,
        required: true,
      },
      {
        id: "holding_solutions_used",
        prompt: "Holding/Storage Solutions Used",
        type: "checkbox",
        options: HOLDING_SOLUTION_OPTIONS,
        required: true,
      },
      {
        id: "grafts_kept_hydrated",
        prompt: "Grafts Kept Hydrated",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: true,
      },
      {
        id: "sorting_performed",
        prompt: "Sorting Performed",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: false,
      },
      {
        id: "implantation_method",
        prompt: "Implantation Method",
        type: "checkbox",
        options: IMPLANTATION_METHOD_OPTIONS,
        required: true,
      },
      {
        id: "implantation_devices_used",
        prompt: "Implantation Devices Used",
        type: "checkbox",
        options: IMPLANTATION_DEVICE_OPTIONS,
        required: true,
      },
      {
        id: "implanted_by",
        prompt: "Implanted By",
        type: "select",
        options: IMPLANTED_BY_OPTIONS,
        required: true,
      },
      {
        id: "intraoperative_adjuncts_used",
        prompt: "Intraoperative Adjuncts Used",
        type: "checkbox",
        options: INTRAOP_ADJUNCT_OPTIONS,
        required: false,
      },
      {
        id: "postoperative_treatments_included",
        prompt: "Post-Operative Treatments Included",
        type: "checkbox",
        options: POSTOP_TREATMENT_OPTIONS,
        required: true,
      },
      {
        id: "postoperative_treatments_recommended",
        prompt: "Post-Operative Treatments Recommended",
        type: "checkbox",
        options: POSTOP_TREATMENT_OPTIONS,
        required: true,
      },
      {
        id: "follow_up_plan_documented",
        prompt: "Follow-Up Plan Documented",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: true,
      },
      {
        id: "outcome_audit_stage",
        prompt: "Outcome Audit Stage",
        type: "select",
        options: OUTCOME_AUDIT_STAGE_OPTIONS,
        required: false,
      },
      {
        id: "growth_outcome_category",
        prompt: "Growth Outcome Category",
        type: "select",
        options: GROWTH_OUTCOME_CATEGORY_OPTIONS,
        required: false,
      },
      {
        id: "donor_healing_category",
        prompt: "Donor Healing Category",
        type: "select",
        options: DONOR_HEALING_CATEGORY_OPTIONS,
        required: false,
      },
      {
        id: "recipient_sites_created_by",
        prompt: "Recipient Sites Created By",
        type: "select",
        options: RECIPIENT_SITES_CREATED_BY_OPTIONS,
        required: true,
      },
      {
        id: "site_creation_method",
        prompt: "Site Creation Method",
        type: "checkbox",
        options: SITE_CREATION_METHOD_OPTIONS,
        required: true,
      },
      {
        id: "dense_packing_attempted",
        prompt: "Dense Packing Attempted",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: false,
      },
      {
        id: "transection_category",
        prompt: "Estimated Transection Category",
        type: "select",
        options: TRANSECTION_CATEGORY_OPTIONS,
        required: false,
      },
    ],
  },
  {
    id: "surgical_metadata_advanced",
    title: "Advanced / Forensic Audit Questions",
    questions: [
      {
        id: "primary_extraction_device",
        prompt: "Primary Extraction Device/System",
        type: "select",
        options: EXTRACTION_DEVICE_OPTIONS,
      },
      {
        id: "extraction_experience_years",
        prompt: "Extraction Experience Years",
        type: "number",
        required: false,
      },
      {
        id: "primary_punch_size",
        prompt: "Primary Punch Size",
        type: "select",
        options: PUNCH_SIZE_OPTIONS,
      },
      {
        id: "primary_punch_type",
        prompt: "Primary Punch Type",
        type: "select",
        options: PUNCH_TYPE_OPTIONS,
      },
      {
        id: "punch_manufacturers_used",
        prompt: "Punch Manufacturers Used",
        type: "checkbox",
        options: PUNCH_MANUFACTURER_OPTIONS,
      },
      {
        id: "primary_holding_solution",
        prompt: "Primary Holding Solution",
        type: "select",
        options: HOLDING_SOLUTION_OPTIONS,
      },
      {
        id: "primary_implantation_device",
        prompt: "Primary Implantation Device",
        type: "select",
        options: IMPLANTATION_DEVICE_OPTIONS,
      },
      {
        id: "implantation_time_minutes",
        prompt: "Implantation Time (minutes)",
        type: "number",
        required: false,
      },
      {
        id: "singles_reserved_for_hairline",
        prompt: "Singles Reserved for Hairline",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: false,
      },
      {
        id: "intraop_prp_used",
        prompt: "PRP Used Intraoperatively",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: false,
      },
      {
        id: "intraop_exosomes_used",
        prompt: "Exosomes Used Intraoperatively",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: false,
      },
      {
        id: "exosome_type",
        prompt: "Exosome Type",
        type: "select",
        options: EXOSOME_TYPE_OPTIONS,
        dependsOn: { questionId: "intraop_exosomes_used", value: "yes" },
        required: false,
      },
      {
        id: "partial_transection_used",
        prompt: "Partial Transection Technique Used",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: false,
      },
      { id: "intraop_adjunct_notes", prompt: "Intraoperative Adjunct Notes", type: "textarea", required: false },
      { id: "extraction_device_change_notes", prompt: "Extraction Device Change Notes", type: "textarea", required: false },
      { id: "punch_size_change_notes", prompt: "Punch Size Change Notes", type: "textarea", required: false },
      { id: "punch_type_change_notes", prompt: "Punch Type Change Notes", type: "textarea", required: false },
      { id: "holding_solution_notes", prompt: "Holding Solution Notes", type: "textarea", required: false },
      { id: "graft_handling_team_notes", prompt: "Graft Handling Team Notes", type: "textarea", required: false },
      { id: "microscopic_inspection_used", prompt: "Microscopic Inspection Used", type: "select", options: BOOLEAN_YES_NO_OPTIONS, required: false },
      { id: "graft_composition_available", prompt: "Graft Composition Count Available", type: "select", options: BOOLEAN_YES_NO_OPTIONS, required: false },
      { id: "graft_tray_quality_rating", prompt: "Graft Tray Quality Rating", type: "select", options: GRAFT_TRAY_QUALITY_RATING_OPTIONS, required: false },
      { id: "graft_sorting_method", prompt: "Graft Sorting Method", type: "checkbox", options: GRAFT_SORTING_METHOD_OPTIONS, required: false },
      { id: "visible_transection_on_tray", prompt: "Visible Transection on Tray", type: "select", options: VISIBLE_TRANSECTION_ON_TRAY_OPTIONS, required: false },
      { id: "graft_tissue_quality_concern", prompt: "Graft Tissue Quality Concern", type: "checkbox", options: GRAFT_TISSUE_QUALITY_CONCERN_OPTIONS, required: false },
      { id: "microscopic_graft_review_available", prompt: "Microscopic Graft Review Available", type: "select", options: BOOLEAN_YES_NO_OPTIONS, required: false },
      { id: "implantation_device_notes", prompt: "Implantation Device Notes", type: "textarea", required: false },
      { id: "popping_issues_observed", prompt: "Popping Issues Observed", type: "select", options: BOOLEAN_YES_NO_OPTIONS, required: false },
      { id: "implant_depth_consistency", prompt: "Implant Depth Consistency", type: "select", options: IMPLANT_DEPTH_CONSISTENCY_OPTIONS, required: false },
      { id: "postoperative_protocol_notes", prompt: "Post-Operative Protocol Notes", type: "textarea", required: false },
      { id: "finasteride_recommended", prompt: "Finasteride Recommended", type: "select", options: BOOLEAN_YES_NO_OPTIONS, required: false },
      { id: "minoxidil_recommended", prompt: "Minoxidil Recommended", type: "select", options: BOOLEAN_YES_NO_OPTIONS, required: false },
      { id: "donor_recovery_protocol_included", prompt: "Donor Recovery Protocol Included", type: "select", options: BOOLEAN_YES_NO_OPTIONS, required: false },
      { id: "patient_satisfaction_category", prompt: "Patient Satisfaction Category", type: "select", options: PATIENT_SATISFACTION_CATEGORY_OPTIONS, required: false },
      { id: "corrective_surgery_likely", prompt: "Corrective Surgery Likely Needed", type: "select", options: BOOLEAN_YES_NO_OPTIONS, required: false },
      { id: "outcome_notes", prompt: "Outcome Notes", type: "textarea", required: false },
      { id: "review_concern_categories", prompt: "Review Concern Categories", type: "checkbox", options: REVIEW_CONCERN_CATEGORY_OPTIONS, required: false },
      { id: "claimed_evidenced_discrepancy", prompt: "Claimed vs Evidenced Discrepancy", type: "select", options: BOOLEAN_YES_NO_OPTIONS, required: false },
      { id: "incomplete_records_flag", prompt: "Incomplete Records Flag", type: "select", options: BOOLEAN_YES_NO_OPTIONS, required: false },
      { id: "case_complexity_rating", prompt: "Case Complexity Rating", type: "select", options: CASE_COMPLEXITY_RATING_OPTIONS, required: false },
      { id: "auditor_confidence_level", prompt: "Auditor Confidence Level", type: "select", options: AUDITOR_CONFIDENCE_LEVEL_OPTIONS, required: false },
      { id: "forensic_notes", prompt: "Freeform Forensic Notes", type: "textarea", required: false },
      { id: "reason_for_intraoperative_changes", prompt: "Reason for Intra-Operative Changes", type: "textarea", required: false },
      { id: "motor_speed_rpm", prompt: "Motor Speed (RPM)", type: "number", required: false },
      { id: "punch_motion", prompt: "Punch Motion", type: "checkbox", options: PUNCH_MOTION_OPTIONS, required: false },
      { id: "transection_rate_percent", prompt: "Transection Rate (%)", type: "number", required: false },
      { id: "buried_graft_rate_percent", prompt: "Buried Graft Rate (%)", type: "number", required: false },
      { id: "extraction_time_minutes", prompt: "Extraction Time (minutes)", type: "number", required: false },
      { id: "slit_orientation", prompt: "Coronal / Sagittal Orientation", type: "select", options: SLIT_ORIENTATION_OPTIONS, required: false },
      { id: "site_instrument_sizes_used", prompt: "Site Instrument Sizes Used", type: "checkbox", options: SITE_INSTRUMENT_SIZE_OPTIONS, required: false },
      { id: "hairline_direction_quality", prompt: "Hairline Direction Quality", type: "select", options: HAIRLINE_DIRECTION_QUALITY_OPTIONS, required: false },
      { id: "angle_direction_notes", prompt: "Angle / Direction Strategy Notes", type: "textarea", required: false },
      { id: "native_hair_protection_strategy", prompt: "Native Hair Protection Strategy", type: "textarea", required: false },
      { id: "out_of_body_time_category", prompt: "Out-of-Body Time Category", type: "select", options: OUT_OF_BODY_TIME_CATEGORY_OPTIONS, required: false },
      { id: "temperature_controlled_storage", prompt: "Temperature Controlled Storage", type: "select", options: TEMPERATURE_CONTROLLED_STORAGE_OPTIONS, required: false },
      { id: "surgeon_vs_technician_split_notes", prompt: "Surgeon vs Technician Split Notes", type: "textarea", required: false },
    ],
  },
  {
    id: "pricing",
    title: "Pricing Structure",
    questions: [
      { id: "cost_range", prompt: "Typical Cost Range for Hair Transplant Procedures", type: "text", placeholder: "$3,000 - $7,000", required: true },
      {
        id: "cost_included",
        prompt: "What Is Typically Included in the Cost?",
        type: "checkbox",
        options: [
          { value: "consultation", label: "Initial Consultation" },
          { value: "preop_tests", label: "Pre-Operative Tests" },
          { value: "procedure", label: "Hair Transplant Procedure" },
          { value: "medications", label: "Post-Operative Medications" },
          { value: "followup", label: "Follow-Up Appointments" },
          { value: "accommodation", label: "Accommodation" },
          { value: "transportation", label: "Transportation" },
          { value: "other", label: "Other" },
        ],
        required: false,
      },
    ],
  },
  {
    id: "quality",
    title: "Quality Assurance",
    questions: [
      { id: "quality_control", prompt: "Quality Control Measures", type: "text", placeholder: "Regular audits, patient follow-up surveys", required: false },
      { id: "equipment_maintenance", prompt: "Equipment Maintenance Schedule", type: "text", placeholder: "Monthly calibration of tools", required: false },
      { id: "safety_protocols", prompt: "Patient Safety Protocols", type: "text", placeholder: "Pre-operative health screenings", required: false },
      { id: "certifications", prompt: "Certifications and Accreditations", type: "text", placeholder: "ISO 9001:2015, JCI Accreditation", required: false },
    ],
  },
  {
    id: "services",
    title: "Patient Services",
    questions: [
      {
        id: "preop_services",
        prompt: "Pre-Operative Services",
        type: "checkbox",
        options: [
          { value: "consult_inperson", label: "Initial Consultation (In-Person)" },
          { value: "consult_virtual", label: "Initial Consultation (Virtual)" },
          { value: "health_screening", label: "Pre-Operative Health Screening" },
          { value: "treatment_planning", label: "Personalized Treatment Planning" },
          { value: "other", label: "Other" },
        ],
        required: false,
      },
      {
        id: "postop_services",
        prompt: "Post-Operative Services",
        type: "checkbox",
        options: [
          { value: "followup", label: "Follow-Up Appointments" },
          { value: "medications", label: "Post-Operative Medications" },
          { value: "care_instructions", label: "Hair Care Instructions" },
          { value: "helpline", label: "24/7 Helpline" },
          { value: "other", label: "Other" },
        ],
        required: false,
      },
      {
        id: "additional_services",
        prompt: "Additional Services",
        type: "checkbox",
        options: [
          { value: "accommodation", label: "Accommodation Arrangements" },
          { value: "transportation", label: "Transportation Services" },
          { value: "translation", label: "Translation Services" },
          { value: "financing", label: "Financing Options" },
          { value: "other", label: "Other" },
        ],
        required: false,
      },
    ],
  },
  {
    id: "technology",
    title: "Technology and Equipment",
    questions: [
      {
        id: "techniques_offered",
        prompt: "Hair Transplant Techniques Offered",
        type: "checkbox",
        options: [
          { value: "fue", label: "FUE" },
          { value: "fut", label: "FUT" },
          { value: "dhi", label: "DHI" },
          { value: "robotic", label: "Robotic" },
          { value: "other", label: "Other" },
        ],
        required: false,
      },
      { id: "advanced_tech", prompt: "Advanced Technologies Used", type: "text", placeholder: "ARTAS Robotic System, Choi Implanter Pens", required: false },
      { id: "graft_preservation", prompt: "Graft Preservation Methods", type: "text", placeholder: "Hypothermosol solution at 4°C", required: false },
    ],
  },
  {
    id: "testimonials",
    title: "Patient Testimonials and Reviews (Optional)",
    questions: [
      { id: "testimonials", prompt: "Patient Testimonials", type: "textarea", required: false },
      { id: "reviews_link", prompt: "Link to Online Reviews", type: "text", placeholder: "www.reviewsite.com/abchairclinic", required: false },
    ],
  },
];

const clinicDefaultSet = new Set<string>(clinicDefaultFields);
export const CLINIC_AUDIT_SECTIONS = CLINIC_AUDIT_SECTIONS_BASE.map((section) => ({
  ...section,
  questions: section.questions.map((q) => ({
    ...q,
    ...(clinicDefaultSet.has(q.id) ? { defaultable: true, defaultSource: "clinic" as const } : {}),
  })),
}));
