// Doctor Audit Form — Surgery Submission / Case Audit
// Target: 6–8 min. Conditional FUE/FUT. Backward compat via doctorAuditSchema.

import { PROCEDURE_TYPE_FUE, PROCEDURE_TYPE_FUT } from "./doctorAuditSchema";
import {
  SUBMISSION_TYPE_OPTIONS,
  AUDIT_DEPTH_TYPE_OPTIONS,
  REQUESTED_BY_OPTIONS,
  REVIEW_PURPOSE_OPTIONS,
  COUNTRY_JURISDICTION_OPTIONS,
  BOOLEAN_YES_NO_OPTIONS,
  ADDITIONAL_OPERATOR_OPTIONS,
  PROCEDURE_TYPE_OPTIONS,
  AREAS_TREATED_OPTIONS,
  PATIENT_AGE_BRACKET_OPTIONS,
  PATIENT_SEX_OPTIONS,
  ETHNICITY_HAIR_BACKGROUND_OPTIONS,
  HAIR_TYPE_CURL_PATTERN_OPTIONS,
  HAIR_CALIBRE_CATEGORY_OPTIONS,
  HAIR_COLOUR_OPTIONS,
  SKIN_HAIR_CONTRAST_OPTIONS,
  PRIMARY_DIAGNOSIS_OPTIONS,
  SECONDARY_DIAGNOSIS_OPTIONS,
  HAIR_LOSS_SCALE_OPTIONS,
  HAIR_LOSS_STABILITY_OPTIONS,
  MINIATURISATION_REGION_OPTIONS,
  SCALP_CONDITION_FLAG_OPTIONS,
  ZONES_PLANNED_OPTIONS,
  CANDIDATE_SUITABILITY_OPTIONS,
  DONOR_QUALITY_RATING_OPTIONS,
  DONOR_DENSITY_RATING_OPTIONS,
  ESTIMATED_DONOR_CAPACITY_OPTIONS,
  OVERHARVESTING_SIGN_OPTIONS,
  EXTRACTION_DEVICE_OPTIONS,
  PUNCH_SIZE_OPTIONS,
  PUNCH_TYPE_OPTIONS,
  PUNCH_MANUFACTURER_OPTIONS,
  HOLDING_SOLUTION_OPTIONS,
  IMPLANTATION_DEVICE_OPTIONS,
  IMPLANTATION_METHOD_OPTIONS,
  IMPLANTED_BY_OPTIONS,
  IMPLANT_DEPTH_CONSISTENCY_OPTIONS,
  INTRAOP_ADJUNCT_OPTIONS,
  EXOSOME_TYPE_OPTIONS,
  POSTOP_TREATMENT_OPTIONS,
  OUTCOME_AUDIT_STAGE_OPTIONS,
  GROWTH_OUTCOME_CATEGORY_OPTIONS,
  DONOR_HEALING_CATEGORY_OPTIONS,
  PATIENT_SATISFACTION_CATEGORY_OPTIONS,
  REVIEW_CONCERN_CATEGORY_OPTIONS,
  CASE_COMPLEXITY_RATING_OPTIONS,
  AUDITOR_CONFIDENCE_LEVEL_OPTIONS,
  GRAFT_TRAY_QUALITY_RATING_OPTIONS,
  GRAFT_SORTING_METHOD_OPTIONS,
  VISIBLE_TRANSECTION_ON_TRAY_OPTIONS,
  GRAFT_TISSUE_QUALITY_CONCERN_OPTIONS,
  EXTRACTION_METHOD_OPTIONS,
  EXTRACTION_TECHNIQUE_OPTIONS,
  EXTRACTION_OPERATOR_OPTIONS,
  TRANSECTION_CATEGORY_OPTIONS,
  RECIPIENT_SITES_CREATED_BY_OPTIONS,
  SITE_CREATION_METHOD_OPTIONS,
  SLIT_ORIENTATION_OPTIONS,
  SITE_INSTRUMENT_SIZE_OPTIONS,
  HAIRLINE_DIRECTION_QUALITY_OPTIONS,
  OUT_OF_BODY_TIME_CATEGORY_OPTIONS,
  PUNCH_MOTION_OPTIONS,
  TEMPERATURE_CONTROLLED_STORAGE_OPTIONS,
} from "./audit/masterSurgicalMetadata";

export type DoctorAuditAnswers = Record<string, string | number | string[] | boolean | null>;

type QuestionDef = {
  id: string;
  prompt: string;
  type: string;
  required?: boolean;
  placeholder?: string;
  help?: string;
  options?: { value: string; label: string }[];
  min?: number;
  max?: number;
  dependsOn?:
    | { questionId: string; value?: string; hasValue?: string }
    | { questionId: string; oneOf: string[] }
    | { or: Array<{ questionId: string; value: string }> };
};

type SectionDef = {
  id: string;
  title: string;
  questions: QuestionDef[];
  showWhen?: { questionId: string; oneOf: string[] };
};

export const DOCTOR_AUDIT_SECTIONS: SectionDef[] = [
  {
    id: "doctor_clinic",
    title: "1. Doctor & Clinic Profile",
    questions: [
      { id: "doctorName", prompt: "Doctor's Name", type: "text", placeholder: "Dr. John Smith", required: true },
      { id: "clinicName", prompt: "Clinic Name", type: "text", placeholder: "ABC Hair Clinic", required: true },
      { id: "clinicLocation", prompt: "Clinic Location", type: "text", placeholder: "City, Country", required: true },
      { id: "medicalDegree", prompt: "Medical Degree", type: "text", placeholder: "MD, Dermatology", required: true },
      {
        id: "yearsPerformingHairTransplants",
        prompt: "Years Performing Hair Transplants",
        type: "number",
        required: true,
        min: 0,
        max: 60,
        help: "0–60 years",
      },
      {
        id: "percentPracticeHairTransplant",
        prompt: "Percent of Practice Devoted to Hair Transplant",
        type: "select",
        required: true,
        options: [
          { value: "lt25", label: "<25%" },
          { value: "25_50", label: "25–50%" },
          { value: "50_75", label: "50–75%" },
          { value: "75_100", label: "75–100%" },
        ],
      },
      {
        id: "memberships",
        prompt: "Memberships",
        type: "checkbox",
        options: [
          { value: "ishrs", label: "ISHRS" },
          { value: "abhrs", label: "ABHRS" },
          { value: "national_board", label: "National Board" },
          { value: "other", label: "Other" },
        ],
        required: false,
      },
      {
        id: "otherMembershipText",
        prompt: "Other membership (please specify)",
        type: "text",
        dependsOn: { questionId: "memberships", hasValue: "other" },
      },
    ],
  },
  {
    id: "case_identity_submission_context",
    title: "2. Basic Audit Questions — Case Identity & Submission Context",
    questions: [
      {
        id: "submission_type",
        prompt: "Audit Submission Type",
        type: "select",
        options: SUBMISSION_TYPE_OPTIONS,
        required: true,
      },
      {
        id: "audit_type",
        prompt: "Audit Type",
        type: "select",
        options: AUDIT_DEPTH_TYPE_OPTIONS,
        required: true,
      },
      { id: "case_id", prompt: "Case ID", type: "text", required: true },
      { id: "clinic_name", prompt: "Clinic Name", type: "text", required: true },
      { id: "clinic_branch", prompt: "Clinic Branch / Location", type: "text" },
      { id: "doctor_name", prompt: "Doctor Name", type: "text", required: true },
      {
        id: "country_jurisdiction",
        prompt: "Country / Jurisdiction",
        type: "select",
        options: COUNTRY_JURISDICTION_OPTIONS,
        required: true,
      },
      { id: "surgery_date", prompt: "Surgery Date", type: "date", required: true },
      {
        id: "multi_day_flag",
        prompt: "Multi-Day Procedure",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: true,
      },
      {
        id: "requested_by",
        prompt: "Requested By",
        type: "select",
        options: REQUESTED_BY_OPTIONS,
        required: true,
      },
      {
        id: "review_purpose",
        prompt: "Review Purpose",
        type: "checkbox",
        options: REVIEW_PURPOSE_OPTIONS,
        required: true,
      },
      {
        id: "previous_surgery_history",
        prompt: "Previous Surgery History",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: true,
      },
      {
        id: "repair_case_flag",
        prompt: "Corrective / Repair Case",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: true,
      },
    ],
  },
  {
    id: "case_identity_submission_context_advanced",
    title: "3. Advanced / Forensic Audit Questions — Case Identity Context",
    questions: [
      {
        id: "additional_operators",
        prompt: "Additional Surgeons / Operators",
        type: "checkbox",
        options: ADDITIONAL_OPERATOR_OPTIONS,
      },
      {
        id: "additional_operators_details",
        prompt: "Additional Operators (Names / Roles)",
        type: "textarea",
      },
      {
        id: "procedure_day_breakdown",
        prompt: "Procedure Day Breakdown",
        type: "textarea",
        dependsOn: { questionId: "multi_day_flag", value: "yes" },
      },
      {
        id: "previous_surgery_details",
        prompt: "Previous Surgery Details",
        type: "textarea",
        dependsOn: { questionId: "previous_surgery_history", value: "yes" },
      },
    ],
  },
  {
    id: "procedure_type_areas_treated_basic",
    title: "4. Basic Audit Questions — Procedure Type & Areas Treated",
    questions: [
      {
        id: "procedure_type",
        prompt: "Procedure Type",
        type: "checkbox",
        options: PROCEDURE_TYPE_OPTIONS,
        required: true,
      },
      {
        id: "primary_procedure_type",
        prompt: "Primary Procedure Type",
        type: "select",
        options: PROCEDURE_TYPE_OPTIONS,
        required: true,
      },
      {
        id: "areas_treated",
        prompt: "Areas Treated",
        type: "checkbox",
        options: AREAS_TREATED_OPTIONS,
        required: true,
      },
      {
        id: "primary_area_treated",
        prompt: "Primary Area Treated",
        type: "select",
        options: AREAS_TREATED_OPTIONS,
      },
      {
        id: "hairline_lowering_flag",
        prompt: "Hairline Lowering Performed",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
      {
        id: "crown_included_flag",
        prompt: "Crown Work Included",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
    ],
  },
  {
    id: "procedure_type_areas_treated_advanced",
    title: "5. Advanced / Forensic Questions — Procedure Type & Areas Treated",
    questions: [
      {
        id: "beard_donor_used",
        prompt: "Beard Donor Used",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
      {
        id: "body_donor_used",
        prompt: "Body Donor Used",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
    ],
  },
  {
    id: "patient_baseline_basic",
    title: "6. Basic Audit Questions — Patient Baseline",
    questions: [
      {
        id: "patient_age_bracket",
        prompt: "Patient Age Bracket",
        type: "select",
        options: PATIENT_AGE_BRACKET_OPTIONS,
        required: true,
      },
      {
        id: "patient_sex",
        prompt: "Sex",
        type: "select",
        options: PATIENT_SEX_OPTIONS,
        required: true,
      },
      {
        id: "ethnicity_hair_background",
        prompt: "Ethnicity / Hair Background",
        type: "checkbox",
        options: ETHNICITY_HAIR_BACKGROUND_OPTIONS,
      },
      {
        id: "hair_type_curl_pattern",
        prompt: "Hair Type / Curl Pattern",
        type: "select",
        options: HAIR_TYPE_CURL_PATTERN_OPTIONS,
        required: true,
      },
      {
        id: "hair_calibre_category",
        prompt: "Hair Calibre Category",
        type: "select",
        options: HAIR_CALIBRE_CATEGORY_OPTIONS,
        required: true,
      },
    ],
  },
  {
    id: "patient_baseline_advanced",
    title: "7. Advanced / Forensic Questions — Patient Baseline",
    questions: [
      {
        id: "hair_shaft_diameter_microns",
        prompt: "Exact Hair Shaft Diameter (microns)",
        type: "number",
        min: 0,
        max: 300,
      },
      {
        id: "hair_colour",
        prompt: "Hair Colour",
        type: "select",
        options: HAIR_COLOUR_OPTIONS,
      },
      {
        id: "skin_hair_contrast",
        prompt: "Skin / Hair Contrast",
        type: "select",
        options: SKIN_HAIR_CONTRAST_OPTIONS,
      },
    ],
  },
  {
    id: "diagnosis_pattern_basic",
    title: "8. Basic Audit Questions — Diagnosis & Hair Loss Pattern",
    questions: [
      {
        id: "primary_diagnosis",
        prompt: "Primary Diagnosis",
        type: "select",
        options: PRIMARY_DIAGNOSIS_OPTIONS,
        required: true,
      },
      {
        id: "hair_loss_scale_used",
        prompt: "Hair Loss Scale Used",
        type: "select",
        options: HAIR_LOSS_SCALE_OPTIONS,
        required: true,
      },
      {
        id: "hair_loss_grade",
        prompt: "Hair Loss Grade",
        type: "text",
        required: true,
        placeholder: "Grade / stage",
      },
      {
        id: "hair_loss_stability",
        prompt: "Hair Loss Stability",
        type: "select",
        options: HAIR_LOSS_STABILITY_OPTIONS,
        required: true,
      },
      {
        id: "miniaturisation_present",
        prompt: "Miniaturisation Present",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: true,
      },
    ],
  },
  {
    id: "diagnosis_pattern_advanced",
    title: "9. Advanced / Forensic Questions — Diagnosis & Hair Loss Pattern",
    questions: [
      {
        id: "secondary_diagnosis",
        prompt: "Secondary Diagnosis / Contributors",
        type: "checkbox",
        options: SECONDARY_DIAGNOSIS_OPTIONS,
      },
      {
        id: "miniaturisation_regions",
        prompt: "Miniaturisation Regions",
        type: "checkbox",
        options: MINIATURISATION_REGION_OPTIONS,
      },
      {
        id: "dupa_retrograde_flag",
        prompt: "DUPA / Retrograde Concern",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
      {
        id: "scalp_condition_flags",
        prompt: "Scalp Condition Flags",
        type: "checkbox",
        options: SCALP_CONDITION_FLAG_OPTIONS,
      },
    ],
  },
  {
    id: "preoperative_planning_basic",
    title: "10. Basic Audit Questions — Pre-Operative Planning",
    questions: [
      {
        id: "planned_graft_count",
        prompt: "Planned Graft Count",
        type: "number",
        required: true,
        min: 0,
        max: 20000,
      },
      {
        id: "actual_graft_count",
        prompt: "Actual Graft Count",
        type: "number",
        required: true,
        min: 0,
        max: 20000,
      },
      {
        id: "zones_planned",
        prompt: "Zones Planned",
        type: "checkbox",
        options: ZONES_PLANNED_OPTIONS,
        required: true,
      },
      {
        id: "future_loss_planning",
        prompt: "Future Loss Planning Considered",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
    ],
  },
  {
    id: "preoperative_planning_advanced",
    title: "11. Advanced / Forensic Questions — Pre-Operative Planning",
    questions: [
      {
        id: "estimated_hair_count",
        prompt: "Estimated Hair Count",
        type: "number",
        min: 0,
        max: 100000,
      },
      {
        id: "density_goal_by_zone",
        prompt: "Density Goal by Zone",
        type: "textarea",
        placeholder: "Zone + target density",
      },
      {
        id: "hairline_design_strategy",
        prompt: "Hairline Design Strategy",
        type: "textarea",
      },
      {
        id: "risk_counselling_documented",
        prompt: "Risk Counselling Documented",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
      {
        id: "candidate_suitability_rating",
        prompt: "Candidate Suitability Rating",
        type: "select",
        options: CANDIDATE_SUITABILITY_OPTIONS,
      },
    ],
  },
  {
    id: "donor_assessment_basic",
    title: "12. Basic Audit Questions — Donor Assessment",
    questions: [
      {
        id: "donor_quality_rating",
        prompt: "Donor Quality Rating",
        type: "select",
        options: DONOR_QUALITY_RATING_OPTIONS,
        required: true,
      },
      {
        id: "donor_density_rating",
        prompt: "Donor Density Rating",
        type: "select",
        options: DONOR_DENSITY_RATING_OPTIONS,
        required: true,
      },
      {
        id: "estimated_donor_capacity",
        prompt: "Estimated Donor Capacity",
        type: "select",
        options: ESTIMATED_DONOR_CAPACITY_OPTIONS,
      },
      {
        id: "estimated_donor_capacity_numeric",
        prompt: "Estimated Donor Capacity (numeric)",
        type: "number",
        min: 0,
        max: 20000,
      },
      {
        id: "safe_donor_zone_assessed",
        prompt: "Safe Donor Zone Assessed",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
        required: true,
      },
      {
        id: "donor_scarring_present",
        prompt: "Scarring Present in Donor",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
      {
        id: "overharvesting_risk_flag",
        prompt: "Overharvesting Risk Flag",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
    ],
  },
  {
    id: "donor_assessment_advanced",
    title: "13. Advanced / Forensic Questions — Donor Assessment",
    questions: [
      {
        id: "donor_density_per_cm2",
        prompt: "Donor Density per cm²",
        type: "number",
        min: 0,
        max: 200,
      },
      {
        id: "avg_hairs_per_graft",
        prompt: "Average Hairs per Graft",
        type: "number",
        min: 0,
        max: 10,
      },
      {
        id: "overharvesting_signs",
        prompt: "Overharvesting Signs Observed",
        type: "checkbox",
        options: OVERHARVESTING_SIGN_OPTIONS,
      },
      {
        id: "donor_mapping_notes",
        prompt: "Donor Mapping Notes",
        type: "textarea",
      },
    ],
  },
  {
    id: "patient_profile",
    title: "14. Patient Profile (De-identified)",
    questions: [
      { id: "patientAge", prompt: "Patient Age", type: "number", required: true, min: 10, max: 100 },
      {
        id: "patientGender",
        prompt: "Patient Gender",
        type: "select",
        required: true,
        options: [
          { value: "male", label: "Male" },
          { value: "female", label: "Female" },
          { value: "other", label: "Other" },
        ],
      },
      {
        id: "hairLossClassification",
        prompt: "Hair Loss Classification",
        type: "select",
        required: true,
        options: [
          { value: "norwood_1", label: "Norwood 1" },
          { value: "norwood_2", label: "Norwood 2" },
          { value: "norwood_3", label: "Norwood 3" },
          { value: "norwood_4", label: "Norwood 4" },
          { value: "norwood_5", label: "Norwood 5" },
          { value: "norwood_6", label: "Norwood 6" },
          { value: "norwood_7", label: "Norwood 7" },
          { value: "ludwig_1", label: "Ludwig 1" },
          { value: "ludwig_2", label: "Ludwig 2" },
          { value: "ludwig_3", label: "Ludwig 3" },
          { value: "diffuse", label: "Diffuse" },
          { value: "other", label: "Other" },
        ],
      },
      {
        id: "hairLossOtherText",
        prompt: "Hair loss classification (if Other)",
        type: "text",
        dependsOn: { questionId: "hairLossClassification", value: "other" },
      },
      {
        id: "donorDensityMeasuredPreOp",
        prompt: "Donor Density Measured Pre-Op",
        type: "select",
        required: true,
        options: [
          { value: "yes_trichoscopy", label: "Yes (Trichoscopy)" },
          { value: "yes_visual", label: "Yes (Visual)" },
          { value: "no", label: "No" },
        ],
      },
      {
        id: "preOpDensityFuPerCm2",
        prompt: "Pre-Op Density (FU/cm²)",
        type: "number",
        min: 0,
        max: 200,
        help: "Optional, 0–200",
      },
    ],
  },
  {
    id: "procedure_overview",
    title: "15. Procedure Overview",
    questions: [
      {
        id: "procedureType",
        prompt: "Procedure Type",
        type: "select",
        required: true,
        options: [
          { value: "fue_manual", label: "FUE (Manual)" },
          { value: "fue_motorized", label: "FUE (Motorized)" },
          { value: "fue_robotic", label: "FUE (Robotic)" },
          { value: "fut", label: "FUT" },
          { value: "combined", label: "Combined FUT + FUE" },
        ],
      },
      {
        id: "totalGraftsExtracted",
        prompt: "Total Grafts Extracted",
        type: "number",
        required: true,
        min: 1,
        max: 10000,
      },
      {
        id: "totalGraftsImplanted",
        prompt: "Total Grafts Implanted",
        type: "number",
        required: true,
        min: 1,
        max: 10000,
      },
      {
        id: "extractionPerformedBy",
        prompt: "Extraction Performed By",
        type: "select",
        required: true,
        options: [
          { value: "doctor", label: "Doctor" },
          { value: "nurse", label: "Nurse" },
          { value: "technician", label: "Technician" },
          { value: "mixed", label: "Mixed" },
        ],
      },
      {
        id: "implantationPerformedBy",
        prompt: "Implantation Performed By",
        type: "select",
        required: true,
        options: [
          { value: "doctor", label: "Doctor" },
          { value: "nurse", label: "Nurse" },
          { value: "technician", label: "Technician" },
          { value: "mixed", label: "Mixed" },
        ],
      },
    ],
  },
  {
    id: "surgical_metadata_basic",
    title: "16. Basic Audit Questions — Surgical Metadata",
    questions: [
      {
        id: "extraction_method",
        prompt: "Extraction Method",
        type: "checkbox",
        required: true,
        options: EXTRACTION_METHOD_OPTIONS,
      },
      {
        id: "extraction_devices_used",
        prompt: "Extraction Devices/Systems Used",
        type: "checkbox",
        required: true,
        options: EXTRACTION_DEVICE_OPTIONS,
        help: "Select all that were used during this surgery.",
      },
      {
        id: "extraction_technique",
        prompt: "Extraction Technique",
        type: "checkbox",
        required: true,
        options: EXTRACTION_TECHNIQUE_OPTIONS,
      },
      {
        id: "extraction_operator",
        prompt: "Extraction Performed By",
        type: "select",
        required: true,
        options: EXTRACTION_OPERATOR_OPTIONS,
      },
      {
        id: "punch_sizes_used",
        prompt: "Punch Sizes Used",
        type: "checkbox",
        required: true,
        options: PUNCH_SIZE_OPTIONS,
      },
      {
        id: "punch_types_used",
        prompt: "Punch Types Used",
        type: "checkbox",
        required: true,
        options: PUNCH_TYPE_OPTIONS,
      },
      {
        id: "holding_solutions_used",
        prompt: "Holding/Storage Solutions Used",
        type: "checkbox",
        required: true,
        options: HOLDING_SOLUTION_OPTIONS,
      },
      {
        id: "grafts_kept_hydrated",
        prompt: "Grafts Kept Hydrated",
        type: "select",
        required: true,
        options: BOOLEAN_YES_NO_OPTIONS,
      },
      {
        id: "sorting_performed",
        prompt: "Sorting Performed",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
      {
        id: "implantation_method",
        prompt: "Implantation Method",
        type: "checkbox",
        required: true,
        options: IMPLANTATION_METHOD_OPTIONS,
      },
      {
        id: "implantation_devices_used",
        prompt: "Implantation Devices Used",
        type: "checkbox",
        required: true,
        options: IMPLANTATION_DEVICE_OPTIONS,
      },
      {
        id: "implanted_by",
        prompt: "Implanted By",
        type: "select",
        required: true,
        options: IMPLANTED_BY_OPTIONS,
      },
      {
        id: "intraoperative_adjuncts_used",
        prompt: "Intraoperative Adjuncts Used",
        type: "checkbox",
        required: false,
        options: INTRAOP_ADJUNCT_OPTIONS,
      },
      {
        id: "postoperative_treatments_included",
        prompt: "Post-Operative Treatments Included",
        type: "checkbox",
        required: true,
        options: POSTOP_TREATMENT_OPTIONS,
      },
      {
        id: "postoperative_treatments_recommended",
        prompt: "Post-Operative Treatments Recommended",
        type: "checkbox",
        required: true,
        options: POSTOP_TREATMENT_OPTIONS,
      },
      {
        id: "follow_up_plan_documented",
        prompt: "Follow-Up Plan Documented",
        type: "select",
        required: true,
        options: BOOLEAN_YES_NO_OPTIONS,
      },
      {
        id: "outcome_audit_stage",
        prompt: "Outcome Audit Stage",
        type: "select",
        required: false,
        options: OUTCOME_AUDIT_STAGE_OPTIONS,
      },
      {
        id: "growth_outcome_category",
        prompt: "Growth Outcome Category",
        type: "select",
        required: false,
        options: GROWTH_OUTCOME_CATEGORY_OPTIONS,
      },
      {
        id: "donor_healing_category",
        prompt: "Donor Healing Category",
        type: "select",
        required: false,
        options: DONOR_HEALING_CATEGORY_OPTIONS,
      },
      {
        id: "transection_category",
        prompt: "Estimated Transection Category",
        type: "select",
        options: TRANSECTION_CATEGORY_OPTIONS,
      },
    ],
  },
  {
    id: "fue_details",
    title: "17. Donor Extraction Details (FUE Only)",
    showWhen: { questionId: "procedureType", oneOf: [...PROCEDURE_TYPE_FUE] },
    questions: [
      {
        id: "fuePunchType",
        prompt: "FUE Punch Type",
        type: "select",
        required: true,
        options: [
          { value: "sharp", label: "Sharp" },
          { value: "dull", label: "Dull" },
          { value: "hybrid", label: "Hybrid" },
          { value: "trumpet", label: "Trumpet" },
          { value: "serrated", label: "Serrated" },
        ],
      },
      {
        id: "fuePunchDiameterRangeMm",
        prompt: "Punch Diameter Range (mm)",
        type: "select",
        required: true,
        options: [
          { value: "lt08", label: "<0.8" },
          { value: "08_09", label: "0.8–0.9" },
          { value: "09_10", label: "0.9–1.0" },
          { value: "gt10", label: ">1.0" },
        ],
      },
      {
        id: "fuePunchMovement",
        prompt: "Punch Movement",
        type: "select",
        required: true,
        options: [
          { value: "full_rotation", label: "Full rotation" },
          { value: "oscillation", label: "Oscillation" },
          { value: "hybrid", label: "Hybrid" },
        ],
      },
      {
        id: "fueDepthControl",
        prompt: "Depth Control",
        type: "select",
        required: true,
        options: [
          { value: "visual_only", label: "Visual only" },
          { value: "guarded", label: "Guarded" },
          { value: "digital", label: "Digital" },
        ],
      },
      {
        id: "fueDocumentedTransectionRatePercent",
        prompt: "Documented Transection Rate (%)",
        type: "number",
        min: 0,
        max: 100,
        help: "Optional",
      },
    ],
  },
  {
    id: "fut_details",
    title: "18. FUT Details (FUT Only)",
    showWhen: { questionId: "procedureType", oneOf: [...PROCEDURE_TYPE_FUT] },
    questions: [
      {
        id: "futBladeType",
        prompt: "Blade Type",
        type: "select",
        required: true,
        options: [
          { value: "single", label: "Single" },
          { value: "double", label: "Double" },
          { value: "parallel", label: "Parallel" },
        ],
      },
      {
        id: "futClosureTechnique",
        prompt: "Closure Technique",
        type: "select",
        required: true,
        options: [
          { value: "standard_layered", label: "Standard layered" },
          { value: "trichophytic", label: "Trichophytic" },
          { value: "staples", label: "Staples" },
        ],
      },
      {
        id: "futMicroscopicDissectionUsed",
        prompt: "Microscopic Dissection Used",
        type: "select",
        required: true,
        options: [
          { value: "yes", label: "Yes" },
          { value: "no", label: "No" },
        ],
      },
    ],
  },
  {
    id: "graft_handling",
    title: "19. Graft Handling & Preservation",
    questions: [
      {
        id: "holdingSolution",
        prompt: "Holding Solution",
        type: "select",
        required: true,
        help: "Critical for graft survival.",
        options: [
          { value: "saline", label: "Saline" },
          { value: "hypothermic", label: "Hypothermic solution" },
          { value: "atp_enhanced", label: "ATP-enhanced" },
          { value: "other", label: "Other" },
        ],
      },
      {
        id: "holdingSolutionOtherText",
        prompt: "Holding solution (if Other)",
        type: "text",
        dependsOn: { questionId: "holdingSolution", value: "other" },
      },
      {
        id: "temperatureControlled",
        prompt: "Temperature Controlled",
        type: "select",
        required: true,
        options: [
          { value: "ice_bowl", label: "Ice bowl" },
          { value: "measured_digital", label: "Measured digital" },
          { value: "no_control", label: "No control" },
        ],
      },
      {
        id: "outOfBodyTimeLogged",
        prompt: "Out-of-Body Time Logged",
        type: "select",
        required: true,
        help: "OBT logging indicates protocol quality.",
        options: [
          { value: "no", label: "No" },
          { value: "estimated", label: "Estimated" },
          { value: "digitally_logged", label: "Digitally logged" },
        ],
      },
      {
        id: "avgOutOfBodyTimeHours",
        prompt: "Avg Out-of-Body Time (hours)",
        type: "number",
        min: 0,
        max: 24,
      },
      {
        id: "microscopeStationsUsed",
        prompt: "Microscope Stations Used",
        type: "select",
        required: true,
        options: [
          { value: "0", label: "0" },
          { value: "1_2", label: "1–2" },
          { value: "3_4", label: "3–4" },
          { value: "5_plus", label: "5+" },
        ],
      },
      {
        id: "microscopeType",
        prompt: "Microscope Type",
        type: "select",
        options: [
          { value: "basic_stereo", label: "Basic stereo" },
          { value: "high_end_stereo", label: "High-end stereo" },
        ],
      },
    ],
  },
  {
    id: "recipient_implantation",
    title: "20. Recipient Site & Implantation",
    questions: [
      {
        id: "recipient_sites_created_by",
        prompt: "Recipient Sites Created By",
        type: "select",
        required: true,
        options: RECIPIENT_SITES_CREATED_BY_OPTIONS,
      },
      {
        id: "site_creation_method",
        prompt: "Site Creation Method",
        type: "checkbox",
        required: true,
        options: SITE_CREATION_METHOD_OPTIONS,
      },
      {
        id: "slit_orientation",
        prompt: "Coronal / Sagittal Orientation",
        type: "select",
        options: SLIT_ORIENTATION_OPTIONS,
      },
      {
        id: "site_instrument_sizes_used",
        prompt: "Site Instrument Sizes Used",
        type: "checkbox",
        options: SITE_INSTRUMENT_SIZE_OPTIONS,
      },
      {
        id: "recipientTool",
        prompt: "Recipient Tool",
        type: "select",
        required: true,
        options: [
          { value: "steel_blade", label: "Steel blade" },
          { value: "sapphire_blade", label: "Sapphire blade" },
          { value: "needle", label: "Needle" },
          { value: "implanter_pen", label: "Implanter pen" },
          { value: "mixed", label: "Mixed" },
        ],
      },
      {
        id: "implantationMethod",
        prompt: "Implantation Method",
        type: "select",
        required: true,
        options: [
          { value: "forceps", label: "Forceps" },
          { value: "premade_slits_forceps", label: "Pre-made slits + forceps" },
          { value: "implanter", label: "Implanter" },
        ],
      },
      {
        id: "dense_packing_attempted",
        prompt: "Dense Packing Attempted",
        type: "select",
        options: [
          { value: "yes", label: "Yes" },
          { value: "no", label: "No" },
        ],
      },
      {
        id: "hairline_direction_quality",
        prompt: "Hairline Direction Quality",
        type: "select",
        options: HAIRLINE_DIRECTION_QUALITY_OPTIONS,
      },
      {
        id: "angle_direction_notes",
        prompt: "Angle / Direction Strategy Notes",
        type: "textarea",
      },
      {
        id: "native_hair_protection_strategy",
        prompt: "Native Hair Protection Strategy",
        type: "textarea",
      },
      {
        id: "implanterType",
        prompt: "Implanter Type",
        type: "select",
        required: true,
        dependsOn: {
          or: [
            { questionId: "recipientTool", value: "implanter_pen" },
            { questionId: "implantationMethod", value: "implanter" },
          ],
        },
        options: [
          { value: "choi", label: "Choi" },
          { value: "lion", label: "Lion" },
          { value: "keep", label: "KEEP" },
          { value: "other", label: "Other" },
        ],
      },
      {
        id: "implanterOtherText",
        prompt: "Implanter type (if Other)",
        type: "text",
        dependsOn: { questionId: "implanterType", value: "other" },
      },
    ],
  },
  {
    id: "donor_management",
    title: "21. Donor Management",
    questions: [
      {
        id: "donorMappingMethod",
        prompt: "Donor Mapping Method",
        type: "select",
        required: true,
        options: [
          { value: "visual_only", label: "Visual only" },
          { value: "measured_zones", label: "Measured zones" },
          { value: "density_mapped_grid", label: "Density-mapped grid" },
        ],
      },
      {
        id: "percentExtractionPerZoneControlled",
        prompt: "Percent Extraction Per Zone Controlled",
        type: "select",
        required: true,
        options: [
          { value: "yes", label: "Yes" },
          { value: "no", label: "No" },
        ],
      },
      {
        id: "postOpDonorDensityMeasured",
        prompt: "Post-Op Donor Density Measured",
        type: "select",
        options: [
          { value: "yes", label: "Yes" },
          { value: "no", label: "No" },
        ],
      },
    ],
  },
  {
    id: "sterility_safety",
    title: "22. Sterility & Safety",
    questions: [
      {
        id: "sterilizationProtocol",
        prompt: "Sterilization Protocol",
        type: "checkbox",
        required: true,
        options: [
          { value: "autoclave", label: "Autoclave" },
          { value: "single_use", label: "Single-use disposables" },
          { value: "chemical", label: "Chemical" },
          { value: "mixed", label: "Mixed" },
        ],
      },
      {
        id: "graftCountDoubleVerified",
        prompt: "Graft Count Double Verified",
        type: "select",
        required: true,
        options: [
          { value: "yes", label: "Yes" },
          { value: "no", label: "No" },
        ],
      },
      {
        id: "intraOpComplications",
        prompt: "Intra-Op Complications",
        type: "select",
        options: [
          { value: "none", label: "None" },
          { value: "bleeding", label: "Bleeding" },
          { value: "popping", label: "Popping" },
          { value: "desiccation", label: "Desiccation" },
          { value: "other", label: "Other" },
        ],
      },
      {
        id: "complicationsOtherText",
        prompt: "Complications (if Other)",
        type: "text",
        dependsOn: { questionId: "intraOpComplications", value: "other" },
      },
    ],
  },
  {
    id: "cost",
    title: "23. Cost & Value Transparency",
    questions: [
      {
        id: "totalProcedureCostUsd",
        prompt: "Total Procedure Cost (USD equivalent)",
        type: "number",
        required: true,
        min: 0,
        max: 500000,
        help: "Store in USD. Currency conversion if needed.",
      },
      {
        id: "costModel",
        prompt: "Cost Model",
        type: "select",
        required: true,
        options: [
          { value: "per_graft", label: "Per graft" },
          { value: "per_session", label: "Per session" },
          { value: "package", label: "Package" },
        ],
      },
      {
        id: "includedInCost",
        prompt: "Included in Cost",
        type: "checkbox",
        options: [
          { value: "prp", label: "PRP" },
          { value: "medications", label: "Medications" },
          { value: "follow_up", label: "Follow-up" },
          { value: "facility", label: "Facility" },
          { value: "anaesthesia", label: "Anaesthesia" },
        ],
      },
    ],
  },
  {
    id: "postop_protocol",
    title: "24. Post-Operative Protocol",
    questions: [
      {
        id: "dhtManagementRecommended",
        prompt: "DHT Management Recommended",
        type: "select",
        required: true,
        options: [
          { value: "yes", label: "Yes" },
          { value: "no", label: "No" },
        ],
      },
      {
        id: "prpPostOpUsed",
        prompt: "PRP Post-Op Used",
        type: "select",
        required: true,
        options: [
          { value: "yes", label: "Yes" },
          { value: "no", label: "No" },
        ],
      },
      {
        id: "followUpScheduleStandardized",
        prompt: "Follow-Up Schedule Standardized",
        type: "select",
        required: true,
        options: [
          { value: "yes", label: "Yes" },
          { value: "no", label: "No" },
        ],
      },
      {
        id: "photoDocumentationRequired12Month",
        prompt: "Photo Documentation Required (12 month)",
        type: "select",
        required: true,
        options: [
          { value: "yes", label: "Yes" },
          { value: "no", label: "No" },
        ],
      },
    ],
  },
  {
    id: "advanced_forensic_metadata",
    title: "25. Advanced / Forensic Audit Questions",
    questions: [
      {
        id: "primary_extraction_device",
        prompt: "Primary Extraction Device/System",
        type: "select",
        options: EXTRACTION_DEVICE_OPTIONS,
      },
      {
        id: "extraction_experience_years",
        prompt: "Extraction Experience Years",
        type: "number",
        min: 0,
        max: 60,
      },
      {
        id: "primary_punch_size",
        prompt: "Primary Punch Size",
        type: "select",
        options: PUNCH_SIZE_OPTIONS,
      },
      {
        id: "primary_punch_type",
        prompt: "Primary Punch Type",
        type: "select",
        options: PUNCH_TYPE_OPTIONS,
      },
      {
        id: "punch_manufacturers_used",
        prompt: "Punch Manufacturers Used",
        type: "checkbox",
        options: PUNCH_MANUFACTURER_OPTIONS,
      },
      {
        id: "primary_holding_solution",
        prompt: "Primary Holding Solution",
        type: "select",
        options: HOLDING_SOLUTION_OPTIONS,
      },
      {
        id: "primary_implantation_device",
        prompt: "Primary Implantation Device",
        type: "select",
        options: IMPLANTATION_DEVICE_OPTIONS,
      },
      {
        id: "implantation_time_minutes",
        prompt: "Implantation Time (minutes)",
        type: "number",
        min: 0,
        max: 1440,
      },
      {
        id: "singles_reserved_for_hairline",
        prompt: "Singles Reserved for Hairline",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
      {
        id: "intraop_prp_used",
        prompt: "PRP Used Intraoperatively",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
      {
        id: "intraop_exosomes_used",
        prompt: "Exosomes Used Intraoperatively",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
      {
        id: "exosome_type",
        prompt: "Exosome Type",
        type: "select",
        options: EXOSOME_TYPE_OPTIONS,
        dependsOn: { questionId: "intraop_exosomes_used", value: "yes" },
      },
      {
        id: "partial_transection_used",
        prompt: "Partial Transection Technique Used",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
      {
        id: "intraop_adjunct_notes",
        prompt: "Intraoperative Adjunct Notes",
        type: "textarea",
      },
      {
        id: "motor_speed_rpm",
        prompt: "Motor Speed (RPM)",
        type: "number",
        min: 0,
        max: 12000,
      },
      {
        id: "punch_motion",
        prompt: "Punch Motion",
        type: "checkbox",
        options: PUNCH_MOTION_OPTIONS,
      },
      {
        id: "transection_rate_percent",
        prompt: "Transection Rate (%)",
        type: "number",
        min: 0,
        max: 100,
      },
      {
        id: "buried_graft_rate_percent",
        prompt: "Buried Graft Rate (%)",
        type: "number",
        min: 0,
        max: 100,
      },
      {
        id: "extraction_time_minutes",
        prompt: "Extraction Time (minutes)",
        type: "number",
        min: 0,
        max: 1440,
      },
      {
        id: "out_of_body_time_category",
        prompt: "Out-of-Body Time Category",
        type: "select",
        options: OUT_OF_BODY_TIME_CATEGORY_OPTIONS,
      },
      {
        id: "temperature_controlled_storage",
        prompt: "Temperature Controlled Storage",
        type: "select",
        options: TEMPERATURE_CONTROLLED_STORAGE_OPTIONS,
      },
      {
        id: "extraction_device_change_notes",
        prompt: "Extraction Device Change Notes",
        type: "textarea",
      },
      {
        id: "punch_size_change_notes",
        prompt: "Punch Size Change Notes",
        type: "textarea",
      },
      {
        id: "punch_type_change_notes",
        prompt: "Punch Type Change Notes",
        type: "textarea",
      },
      {
        id: "holding_solution_notes",
        prompt: "Holding Solution Notes",
        type: "textarea",
      },
      {
        id: "graft_handling_team_notes",
        prompt: "Graft Handling Team Notes",
        type: "textarea",
      },
      {
        id: "microscopic_inspection_used",
        prompt: "Microscopic Inspection Used",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
      {
        id: "graft_composition_available",
        prompt: "Graft Composition Count Available",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
      {
        id: "graft_tray_quality_rating",
        prompt: "Graft Tray Quality Rating",
        type: "select",
        options: GRAFT_TRAY_QUALITY_RATING_OPTIONS,
      },
      {
        id: "graft_sorting_method",
        prompt: "Graft Sorting Method",
        type: "checkbox",
        options: GRAFT_SORTING_METHOD_OPTIONS,
      },
      {
        id: "visible_transection_on_tray",
        prompt: "Visible Transection on Tray",
        type: "select",
        options: VISIBLE_TRANSECTION_ON_TRAY_OPTIONS,
      },
      {
        id: "graft_tissue_quality_concern",
        prompt: "Graft Tissue Quality Concern",
        type: "checkbox",
        options: GRAFT_TISSUE_QUALITY_CONCERN_OPTIONS,
      },
      {
        id: "microscopic_graft_review_available",
        prompt: "Microscopic Graft Review Available",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
      {
        id: "implantation_device_notes",
        prompt: "Implantation Device Notes",
        type: "textarea",
      },
      {
        id: "popping_issues_observed",
        prompt: "Popping Issues Observed",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
      {
        id: "implant_depth_consistency",
        prompt: "Implant Depth Consistency",
        type: "select",
        options: IMPLANT_DEPTH_CONSISTENCY_OPTIONS,
      },
      {
        id: "postoperative_protocol_notes",
        prompt: "Post-Operative Protocol Notes",
        type: "textarea",
      },
      {
        id: "finasteride_recommended",
        prompt: "Finasteride Recommended",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
      {
        id: "minoxidil_recommended",
        prompt: "Minoxidil Recommended",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
      {
        id: "donor_recovery_protocol_included",
        prompt: "Donor Recovery Protocol Included",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
      {
        id: "patient_satisfaction_category",
        prompt: "Patient Satisfaction Category",
        type: "select",
        options: PATIENT_SATISFACTION_CATEGORY_OPTIONS,
      },
      {
        id: "corrective_surgery_likely",
        prompt: "Corrective Surgery Likely Needed",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
      {
        id: "outcome_notes",
        prompt: "Outcome Notes",
        type: "textarea",
      },
      {
        id: "review_concern_categories",
        prompt: "Review Concern Categories",
        type: "checkbox",
        options: REVIEW_CONCERN_CATEGORY_OPTIONS,
      },
      {
        id: "claimed_evidenced_discrepancy",
        prompt: "Claimed vs Evidenced Discrepancy",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
      {
        id: "incomplete_records_flag",
        prompt: "Incomplete Records Flag",
        type: "select",
        options: BOOLEAN_YES_NO_OPTIONS,
      },
      {
        id: "case_complexity_rating",
        prompt: "Case Complexity Rating",
        type: "select",
        options: CASE_COMPLEXITY_RATING_OPTIONS,
      },
      {
        id: "auditor_confidence_level",
        prompt: "Auditor Confidence Level",
        type: "select",
        options: AUDITOR_CONFIDENCE_LEVEL_OPTIONS,
      },
      {
        id: "forensic_notes",
        prompt: "Freeform Forensic Notes",
        type: "textarea",
      },
      {
        id: "reason_for_intraoperative_changes",
        prompt: "Reason for Intra-Operative Changes",
        type: "textarea",
      },
      {
        id: "surgeon_vs_technician_split_notes",
        prompt: "Surgeon vs Technician Split Notes",
        type: "textarea",
      },
    ],
  },
  {
    id: "self_assessment",
    title: "26. Doctor Self-Assessment",
    questions: [
      {
        id: "estimatedGraftSurvivalPercent",
        prompt: "Estimated Graft Survival (%)",
        type: "number",
        min: 0,
        max: 100,
        help: "Optional",
      },
      {
        id: "overallCaseSuccessRating",
        prompt: "Overall Case Success",
        type: "rating",
        min: 1,
        max: 5,
        required: true,
        help: "1–5 stars",
      },
      {
        id: "notesOptional",
        prompt: "Additional Notes",
        type: "textarea",
        placeholder: "Optional comments",
      },
    ],
  },
];
