// Patient Audit Form v2 — streamlined, data-rich, ~5–6 min
// Optimized for patients who may not know technical details
// "Not Sure" / "Not clear" options to avoid bad data
//
// Canonical field ids and option *values* live here for payloads and validation.
// Localized *display* (prompts/help/labels) is layered in `src/lib/patientIntake/intakeDisplayI18n.ts` (Batch 12+).

// Patient answers are primarily primitive values, but we also support nested structured objects
// for progressive “advanced forensic” inputs (backward-compatible).
export type PatientAuditAnswers = Record<string, unknown>;

export const PATIENT_AUDIT_SECTIONS: Array<{
  id: string;
  title: string;
  description?: string;
  advanced?: boolean;
  questions: PatientFormQuestion[];
}> = [
  {
    id: "clinic_procedure",
    title: "Clinic & Procedure Details",
    questions: [
      { id: "clinic_name", prompt: "Clinic Name", type: "text", placeholder: "ABC Hair Clinic", required: true },
      {
        id: "clinic_country",
        prompt: "Clinic Country",
        type: "select",
        options: [
          { value: "turkey", label: "Turkey" },
          { value: "spain", label: "Spain" },
          { value: "india", label: "India" },
          { value: "thailand", label: "Thailand" },
          { value: "mexico", label: "Mexico" },
          { value: "brazil", label: "Brazil" },
          { value: "argentina", label: "Argentina" },
          { value: "colombia", label: "Colombia" },
          { value: "australia", label: "Australia" },
          { value: "uk", label: "United Kingdom" },
          { value: "usa", label: "United States" },
          { value: "canada", label: "Canada" },
          { value: "uae", label: "UAE" },
          { value: "belgium", label: "Belgium" },
          { value: "germany", label: "Germany" },
          { value: "poland", label: "Poland" },
          { value: "greece", label: "Greece" },
          { value: "other", label: "Other" },
        ],
        required: true,
      },
      {
        id: "clinic_country_other",
        prompt: "Clinic country (if Other)",
        type: "text",
        placeholder: "e.g. Portugal",
        required: false,
        dependsOn: { questionId: "clinic_country", value: "other" },
      },
      { id: "clinic_city", prompt: "Clinic City", type: "text", placeholder: "Istanbul", required: true },
      { id: "procedure_date", prompt: "Date of Procedure", type: "date", required: true },
      {
        id: "procedure_type",
        prompt: "Type of Procedure",
        type: "select",
        options: [
          { value: "fue", label: "FUE" },
          { value: "fut", label: "FUT" },
          { value: "dhi", label: "DHI" },
          { value: "robotic", label: "Robotic" },
          { value: "not_sure", label: "Not Sure" },
          { value: "other", label: "Other" },
        ],
        required: true,
        help: "Choose what you were told; 'Not Sure' is okay.",
      },
      {
        id: "procedure_type_other",
        prompt: "Procedure type (if Other)",
        type: "text",
        placeholder: "e.g. Combined",
        required: false,
        dependsOn: { questionId: "procedure_type", value: "other" },
      },
      { id: "surgeon_name", prompt: "Surgeon's Name (optional)", type: "text", placeholder: "Dr. Smith", required: false },
      { id: "patient_name", prompt: "Your Name (optional, for privacy)", type: "text", placeholder: "John Doe", required: false },
    ],
  },
  {
    id: "transparency",
    title: "Transparency & Process",
    questions: [
      { id: "preop_consult", prompt: "Did you have a pre-operative consultation?", type: "yesno", required: true },
      {
        id: "doctor_present_extraction",
        prompt: "Was a doctor present during graft extraction?",
        type: "select",
        options: [
          { value: "yes", label: "Yes" },
          { value: "no", label: "No" },
          { value: "not_sure", label: "Not Sure" },
        ],
        required: true,
      },
      {
        id: "doctor_present_implant",
        prompt: "Was a doctor present during graft implantation?",
        type: "select",
        options: [
          { value: "yes", label: "Yes" },
          { value: "no", label: "No" },
          { value: "not_sure", label: "Not Sure" },
        ],
        required: true,
      },
      { id: "graft_number_disclosed", prompt: "Were you told the graft count?", type: "yesno", required: true },
      {
        id: "graft_number_received",
        prompt: "Graft number (if you were given one)",
        type: "number",
        min: 0,
        max: 20000,
        placeholder: "e.g. 3500",
        required: false,
        help: "Only if you were given a number.",
      },
      {
        id: "donor_shaving",
        prompt: "Donor area shaving",
        type: "select",
        options: [
          { value: "full_shave", label: "Yes (full shave)" },
          { value: "partial_shave", label: "Partial shave" },
          { value: "no", label: "No" },
        ],
        required: true,
      },
      {
        id: "surgery_duration",
        prompt: "Surgery duration",
        type: "select",
        options: [
          { value: "under_4h", label: "Less than 4 hours" },
          { value: "4_6h", label: "4–6 hours" },
          { value: "6_8h", label: "6–8 hours" },
          { value: "8_plus", label: "8+ hours" },
        ],
        required: true,
      },
    ],
  },
  {
    id: "cost",
    title: "Cost & Value Transparency",
    questions: [
      {
        id: "total_paid_currency",
        prompt: "Currency",
        type: "select",
        options: [
          { value: "usd", label: "USD ($)" },
          { value: "eur", label: "EUR (€)" },
          { value: "gbp", label: "GBP (£)" },
          { value: "try", label: "TRY (₺)" },
          { value: "inr", label: "INR (₹)" },
          { value: "thb", label: "THB (฿)" },
          { value: "mxn", label: "MXN ($)" },
          { value: "aud", label: "AUD ($)" },
          { value: "other", label: "Other" },
        ],
        required: true,
      },
      {
        id: "total_paid_currency_other",
        prompt: "Currency (if Other)",
        type: "text",
        placeholder: "e.g. CAD, CHF",
        required: false,
        dependsOn: { questionId: "total_paid_currency", value: "other" },
      },
      {
        id: "total_paid_amount",
        prompt: "Total Amount Paid",
        type: "number",
        min: 0,
        max: 500000,
        placeholder: "5000",
        required: true,
      },
      {
        id: "cost_model",
        prompt: "How was the cost structured?",
        type: "select",
        options: [
          { value: "per_graft", label: "Per graft" },
          { value: "per_session", label: "Per session" },
          { value: "package", label: "Package" },
          { value: "not_clear", label: "Not clear" },
        ],
        required: true,
      },
      {
        id: "what_included",
        prompt: "What was included?",
        type: "checkbox",
        options: [
          { value: "procedure", label: "Procedure" },
          { value: "medications", label: "Medications" },
          { value: "followup", label: "Follow-up" },
          { value: "prp", label: "PRP" },
          { value: "accommodation", label: "Accommodation" },
          { value: "transport", label: "Transport" },
          { value: "other", label: "Other" },
        ],
        required: false,
      },
      {
        id: "what_included_other",
        prompt: "Other inclusions (please specify)",
        type: "text",
        required: false,
        dependsOn: { questionId: "what_included", hasValue: "other" },
      },
    ],
  },
  {
    id: "surgical_experience",
    title: "Surgical Experience",
    questions: [
      {
        id: "pain_level",
        prompt: "Pain level during surgery",
        type: "slider",
        min: 1,
        max: 10,
        help: "1 = No pain, 10 = Severe pain",
        required: true,
      },
      {
        id: "post_op_swelling",
        prompt: "Post-operative swelling",
        type: "select",
        options: [
          { value: "none", label: "None" },
          { value: "mild", label: "Mild" },
          { value: "moderate", label: "Moderate" },
          { value: "severe", label: "Severe" },
        ],
        required: true,
      },
      {
        id: "bleeding_issue",
        prompt: "Any significant bleeding?",
        type: "select",
        options: [
          { value: "yes", label: "Yes" },
          { value: "no", label: "No" },
          { value: "not_sure", label: "Not Sure" },
        ],
        required: true,
      },
    ],
  },
  {
    id: "recovery",
    title: "Recovery & Complications",
    questions: [
      {
        id: "recovery_time",
        prompt: "Recovery time",
        type: "select",
        options: [
          { value: "under_1_week", label: "Less than 1 week" },
          { value: "1_2_weeks", label: "1–2 weeks" },
          { value: "2_4_weeks", label: "2–4 weeks" },
          { value: "4_plus_weeks", label: "4+ weeks" },
        ],
        required: true,
      },
      {
        id: "shock_loss",
        prompt: "Did you experience shock loss (temporary shedding)?",
        type: "select",
        options: [
          { value: "yes", label: "Yes" },
          { value: "no", label: "No" },
          { value: "not_sure", label: "Not Sure" },
        ],
        required: true,
      },
      { id: "complications", prompt: "Any complications?", type: "yesno", required: true },
      {
        id: "complications_details",
        prompt: "Complication details",
        type: "textarea",
        placeholder: "Describe what happened",
        required: false,
        dependsOn: { questionId: "complications", value: "yes" },
      },
    ],
  },
  {
    id: "results",
    title: "Results (Contextualized)",
    questions: [
      {
        id: "months_since",
        prompt: "Months since procedure",
        type: "select",
        options: [
          { value: "under_3", label: "Less than 3 months" },
          { value: "3_6", label: "3–6 months" },
          { value: "6_9", label: "6–9 months" },
          { value: "9_12", label: "9–12 months" },
          { value: "12_plus", label: "12+ months" },
        ],
        required: true,
      },
      {
        id: "density_satisfaction",
        prompt: "Density satisfaction",
        type: "rating",
        min: 1,
        max: 5,
        help: "1 = Very dissatisfied, 5 = Very satisfied",
        required: true,
      },
      {
        id: "hairline_naturalness",
        prompt: "Hairline naturalness",
        type: "rating",
        min: 1,
        max: 5,
        help: "1 = Poor, 5 = Excellent",
        required: true,
      },
      {
        id: "donor_appearance",
        prompt: "Donor area appearance",
        type: "rating",
        min: 1,
        max: 5,
        help: "1 = Poor, 5 = Excellent",
        required: true,
      },
      {
        id: "would_repeat",
        prompt: "Would you repeat the procedure with this clinic?",
        type: "select",
        options: [
          { value: "yes", label: "Yes" },
          { value: "no", label: "No" },
          { value: "not_sure", label: "Not Sure" },
        ],
        required: true,
      },
      { id: "would_recommend", prompt: "Would you recommend this clinic?", type: "yesno", required: true },
    ],
  },
  // -----------------------------
  // Advanced forensic intake (optional) — stored under enhanced_patient_answers.*
  // Steps match the “progressive intake” requirement and can be toggled on/off in UI.
  // -----------------------------
  {
    id: "adv_basics",
    title: "Basics",
    advanced: true,
    description: "Optional. Helps the AI model contextualize risk and healing stage.",
    questions: [
      {
        id: "enhanced_patient_answers.baseline.patient_age",
        prompt: "Age",
        type: "number",
        min: 0,
        max: 110,
        placeholder: "e.g. 34",
        required: false,
      },
      {
        id: "enhanced_patient_answers.baseline.patient_sex",
        prompt: "Sex",
        type: "select",
        options: [
          { value: "Male", label: "Male" },
          { value: "Female", label: "Female" },
          { value: "Intersex", label: "Intersex" },
          { value: "Prefer not to say", label: "Prefer not to say" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.baseline.smoking_status",
        prompt: "Smoking status",
        type: "select",
        options: [
          { value: "No", label: "No" },
          { value: "Occasionally", label: "Occasionally" },
          { value: "Daily", label: "Daily" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.baseline.alcohol_frequency",
        prompt: "Alcohol frequency (optional)",
        type: "select",
        options: [
          { value: "Rare", label: "Rare" },
          { value: "Weekly", label: "Weekly" },
          { value: "Daily", label: "Daily" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.baseline.diabetes",
        prompt: "Diabetes",
        type: "select",
        options: [
          { value: "No", label: "No" },
          { value: "Type1", label: "Type 1" },
          { value: "Type2", label: "Type 2" },
          { value: "Not sure", label: "Not sure" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.baseline.autoimmune_conditions",
        prompt: "Autoimmune conditions (optional)",
        type: "textarea",
        placeholder: "e.g. alopecia areata, lupus, psoriasis (if known)",
        required: false,
      },
      {
        id: "enhanced_patient_answers.baseline.thyroid_issues",
        prompt: "Thyroid issues",
        type: "select",
        options: [
          { value: "No", label: "No" },
          { value: "Yes", label: "Yes" },
          { value: "Not sure", label: "Not sure" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.baseline.clotting_disorders",
        prompt: "Clotting disorders",
        type: "select",
        options: [
          { value: "No", label: "No" },
          { value: "Yes", label: "Yes" },
          { value: "Not sure", label: "Not sure" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.baseline.blood_thinners",
        prompt: "Blood thinners (optional)",
        type: "text",
        placeholder: "Name(s) if applicable",
        required: false,
      },
      {
        id: "enhanced_patient_answers.baseline.steroid_use",
        prompt: "Steroid use (optional)",
        type: "text",
        placeholder: "If applicable (no dosage needed)",
        required: false,
      },
      {
        id: "enhanced_patient_answers.baseline.previous_scalp_surgeries",
        prompt: "Previous scalp surgeries (optional)",
        type: "textarea",
        placeholder: "e.g. prior transplant, scalp reduction",
        required: false,
      },
    ],
  },
  {
    id: "adv_hair_biology",
    title: "Hair & Biology",
    advanced: true,
    description: "Optional. Improves progression and donor-risk inference.",
    questions: [
      {
        id: "enhanced_patient_answers.hair_biology.hair_loss_duration_years",
        prompt: "Hair loss duration (years)",
        type: "number",
        min: 0,
        max: 80,
        placeholder: "e.g. 6",
        required: false,
      },
      {
        id: "enhanced_patient_answers.hair_biology.hair_loss_progression_speed",
        prompt: "Progression speed",
        type: "select",
        options: [
          { value: "Slow", label: "Slow" },
          { value: "Moderate", label: "Moderate" },
          { value: "Rapid", label: "Rapid" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.hair_biology.family_history_strength",
        prompt: "Family history strength",
        type: "select",
        options: [
          { value: "None", label: "None" },
          { value: "Mild", label: "Mild" },
          { value: "Strong", label: "Strong" },
          { value: "Unknown", label: "Unknown" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.hair_biology.current_medications_for_hair",
        prompt: "Current hair medications (optional)",
        type: "textarea",
        placeholder: "List what you’re using (if any)",
        required: false,
      },
      {
        id: "enhanced_patient_answers.hair_biology.stopped_medications_recently",
        prompt: "Stopped hair meds recently? (optional)",
        type: "boolean",
        required: false,
      },
      {
        id: "enhanced_patient_answers.hair_biology.scalp_condition_history",
        prompt: "Scalp condition history (optional)",
        type: "textarea",
        placeholder: "e.g. dermatitis, folliculitis, itching",
        required: false,
      },
      {
        id: "enhanced_patient_answers.hair_biology.previous_prp_or_exosomes",
        prompt: "Previous PRP or exosomes? (optional)",
        type: "boolean",
        required: false,
      },
    ],
  },
  {
    id: "adv_procedure_details",
    title: "Procedure Details",
    advanced: true,
    description: "Optional. Improves technician-role and planning inference.",
    questions: [
      {
        id: "enhanced_patient_answers.procedure_execution.technician_role_extraction",
        prompt: "Who performed extraction?",
        type: "select",
        options: [
          { value: "Doctor", label: "Doctor" },
          { value: "Technician", label: "Technician" },
          { value: "Mixed", label: "Mixed" },
          { value: "Not sure", label: "Not sure" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.procedure_execution.technician_role_implantation",
        prompt: "Who performed implantation?",
        type: "select",
        options: [
          { value: "Doctor", label: "Doctor" },
          { value: "Technician", label: "Technician" },
          { value: "Mixed", label: "Mixed" },
          { value: "Not sure", label: "Not sure" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.procedure_execution.grafts_claimed_total",
        prompt: "Total grafts claimed (optional)",
        type: "number",
        min: 0,
        max: 25000,
        placeholder: "e.g. 3800",
        required: false,
      },
      {
        id: "enhanced_patient_answers.procedure_execution.graft_ratio",
        prompt: "Graft ratio (optional)",
        type: "number",
        min: 0,
        max: 10,
        placeholder: "If you were told a ratio",
        required: false,
      },
      {
        id: "enhanced_patient_answers.procedure_execution.hairline_drawn_by_doctor",
        prompt: "Hairline drawn by doctor?",
        type: "select",
        options: [
          { value: "Yes", label: "Yes" },
          { value: "Technician", label: "Technician" },
          { value: "Not sure", label: "Not sure" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.procedure_execution.single_hair_grafts_front",
        prompt: "Single-hair grafts used in the front zone?",
        type: "select",
        options: [
          { value: "Yes", label: "Yes" },
          { value: "No", label: "No" },
          { value: "Not sure", label: "Not sure" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.procedure_execution.crown_pattern_discussed",
        prompt: "Crown pattern discussed (if crown work was done)?",
        type: "select",
        options: [
          { value: "Yes", label: "Yes" },
          { value: "No", label: "No" },
          { value: "Not sure", label: "Not sure" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.donor_profile.pre_existing_donor_thinning",
        prompt: "Pre-existing donor thinning",
        type: "select",
        options: [
          { value: "None", label: "None" },
          { value: "Mild", label: "Mild" },
          { value: "Moderate", label: "Moderate" },
          { value: "Severe", label: "Severe" },
          { value: "Not sure", label: "Not sure" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.donor_profile.donor_density_measured",
        prompt: "Was donor density measured?",
        type: "select",
        options: [
          { value: "Numeric", label: "Yes (numeric measurement)" },
          { value: "Visual only", label: "Visual only" },
          { value: "No", label: "No" },
          { value: "Not sure", label: "Not sure" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.donor_profile.donor_area_marked_preop",
        prompt: "Donor area marked pre-op?",
        type: "select",
        options: [
          { value: "Yes", label: "Yes" },
          { value: "No", label: "No" },
          { value: "Not sure", label: "Not sure" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.donor_profile.donor_extraction_pattern_observed",
        prompt: "Extraction pattern observed (optional)",
        type: "select",
        options: [
          { value: "Uniform", label: "Uniform" },
          { value: "Clustered", label: "Clustered" },
          { value: "Not sure", label: "Not sure" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.donor_profile.multiple_days_of_extraction",
        prompt: "Multiple days of extraction? (optional)",
        type: "boolean",
        required: false,
      },
    ],
  },
  {
    id: "adv_graft_handling",
    title: "Graft Handling",
    advanced: true,
    description: "Optional. Strongly improves desiccation and viability inference.",
    questions: [
      {
        id: "enhanced_patient_answers.graft_handling.out_of_body_time_estimate",
        prompt: "Out-of-body time estimate (optional)",
        type: "select",
        options: [
          { value: "Less than 1h", label: "Less than 1 hour" },
          { value: "1-2h", label: "1–2 hours" },
          { value: "2-4h", label: "2–4 hours" },
          { value: "4h+", label: "4+ hours" },
          { value: "Not sure", label: "Not sure" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.graft_handling.storage_solution",
        prompt: "Storage solution (optional)",
        type: "select",
        options: [
          { value: "Saline", label: "Saline" },
          { value: "HypoThermosol", label: "HypoThermosol" },
          { value: "PRP", label: "PRP" },
          { value: "Other", label: "Other" },
          { value: "Not sure", label: "Not sure" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.graft_handling.temperature_control",
        prompt: "Temperature control (optional)",
        type: "select",
        options: [
          { value: "Chilled", label: "Chilled" },
          { value: "Room temp", label: "Room temperature" },
          { value: "Not sure", label: "Not sure" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.graft_handling.grafts_kept_hydrated",
        prompt: "Grafts kept hydrated? (optional)",
        type: "select",
        options: [
          { value: "Yes", label: "Yes" },
          { value: "No", label: "No" },
          { value: "Not sure", label: "Not sure" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.graft_handling.exposed_to_air",
        prompt: "Exposed to air (optional)",
        type: "select",
        options: [
          { value: "Never", label: "Never" },
          { value: "Occasionally", label: "Occasionally" },
          { value: "Frequently", label: "Frequently" },
          { value: "Not sure", label: "Not sure" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.graft_handling.long_breaks_during_surgery",
        prompt: "Long breaks during surgery? (optional)",
        type: "select",
        options: [
          { value: "No", label: "No" },
          { value: "Under 30min", label: "Under 30 minutes" },
          { value: "Over 1h", label: "Over 1 hour" },
          { value: "Not sure", label: "Not sure" },
        ],
        required: false,
      },
    ],
  },
  {
    id: "adv_healing",
    title: "Healing",
    advanced: true,
    description: "Optional. Improves stage inference and complication risk framing.",
    questions: [
      {
        id: "enhanced_patient_answers.healing_course.current_month_postop",
        prompt: "Current months post-op (optional)",
        type: "number",
        min: 0,
        max: 48,
        placeholder: "e.g. 8",
        required: false,
      },
      {
        id: "enhanced_patient_answers.healing_course.shedding_start_week",
        prompt: "Shedding start (week, optional)",
        type: "number",
        min: 0,
        max: 24,
        placeholder: "e.g. 3",
        required: false,
      },
      {
        id: "enhanced_patient_answers.healing_course.shedding_severity",
        prompt: "Shedding severity (optional)",
        type: "select",
        options: [
          { value: "None", label: "None" },
          { value: "Mild", label: "Mild" },
          { value: "Moderate", label: "Moderate" },
          { value: "Heavy", label: "Heavy" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.healing_course.regrowth_start_month",
        prompt: "Regrowth start (month, optional)",
        type: "number",
        min: 0,
        max: 24,
        placeholder: "e.g. 4",
        required: false,
      },
      {
        id: "enhanced_patient_answers.healing_course.visible_density_improvement",
        prompt: "Visible density improvement (optional)",
        type: "select",
        options: [
          { value: "None", label: "None" },
          { value: "Mild", label: "Mild" },
          { value: "Moderate", label: "Moderate" },
          { value: "Significant", label: "Significant" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.healing_course.uneven_growth_present",
        prompt: "Uneven growth present? (optional)",
        type: "boolean",
        required: false,
      },
      {
        id: "enhanced_patient_answers.healing_course.persistent_redness",
        prompt: "Persistent redness? (optional)",
        type: "boolean",
        required: false,
      },
      {
        id: "enhanced_patient_answers.healing_course.recipient_irregularities",
        prompt: "Recipient irregularities (optional)",
        type: "select",
        options: [
          { value: "Cobblestoning", label: "Cobblestoning" },
          { value: "Pitting", label: "Pitting" },
          { value: "Ridges", label: "Ridges" },
          { value: "None", label: "None" },
          { value: "Not sure", label: "Not sure" },
        ],
        required: false,
      },
    ],
  },
  {
    id: "adv_current_status",
    title: "Current Status",
    advanced: true,
    description: "Optional. Improves aesthetic consistency + patient experience context.",
    questions: [
      {
        id: "enhanced_patient_answers.aesthetics.hairline_height_changed_cm",
        prompt: "Hairline height changed (cm, optional)",
        type: "number",
        min: -10,
        max: 10,
        placeholder: "e.g. 1.5",
        required: false,
      },
      {
        id: "enhanced_patient_answers.aesthetics.temple_points_reconstructed",
        prompt: "Temple points reconstructed? (optional)",
        type: "boolean",
        required: false,
      },
      {
        id: "enhanced_patient_answers.aesthetics.direction_matches_native",
        prompt: "Direction matches native hair? (optional)",
        type: "select",
        options: [
          { value: "Yes", label: "Yes" },
          { value: "Slight mismatch", label: "Slight mismatch" },
          { value: "No", label: "No" },
          { value: "Not sure", label: "Not sure" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.aesthetics.crown_swirl_matches",
        prompt: "Crown swirl matches? (optional)",
        type: "select",
        options: [
          { value: "Yes", label: "Yes" },
          { value: "No", label: "No" },
          { value: "Not applicable", label: "Not applicable" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.experience.communication_rating",
        prompt: "Communication rating",
        type: "rating",
        min: 1,
        max: 5,
        required: false,
      },
      {
        id: "enhanced_patient_answers.experience.transparency_rating",
        prompt: "Transparency rating",
        type: "rating",
        min: 1,
        max: 5,
        required: false,
      },
      {
        id: "enhanced_patient_answers.experience.felt_rushed",
        prompt: "Felt rushed? (optional)",
        type: "boolean",
        required: false,
      },
      {
        id: "enhanced_patient_answers.experience.felt_informed",
        prompt: "Felt informed?",
        type: "select",
        options: [
          { value: "Yes", label: "Yes" },
          { value: "Somewhat", label: "Somewhat" },
          { value: "No", label: "No" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.experience.legal_or_refund_dispute",
        prompt: "Legal or refund dispute?",
        type: "select",
        options: [
          { value: "No", label: "No" },
          { value: "Ongoing", label: "Ongoing" },
          { value: "Resolved", label: "Resolved" },
        ],
        required: false,
      },
      {
        id: "enhanced_patient_answers.experience.current_satisfaction",
        prompt: "Current satisfaction (0–10)",
        type: "number",
        min: 0,
        max: 10,
        placeholder: "e.g. 7",
        required: false,
      },
      {
        id: "enhanced_patient_answers.experience.biggest_concern_now",
        prompt: "Biggest concern right now (optional)",
        type: "textarea",
        placeholder: "What’s your main concern today?",
        required: false,
      },
      {
        id: "enhanced_patient_answers.experience.considering_revision",
        prompt: "Considering revision?",
        type: "select",
        options: [
          { value: "Yes", label: "Yes" },
          { value: "No", label: "No" },
          { value: "Unsure", label: "Unsure" },
        ],
        required: false,
      },
    ],
  },
];

export type PatientFormQuestion = {
  id: string;
  prompt: string;
  type: string;
  required?: boolean;
  placeholder?: string;
  help?: string;
  options?: { value: string; label: string }[];
  min?: number;
  max?: number;
  dependsOn?: { questionId: string; value?: string; hasValue?: string };
};
