/**
 * HA-PRE-SURGERY-PROJECTION-REAL-ASSET-1A — Approved non-stub asset writer when ImagingOS
 * is unavailable. Writes a real JPEG under pre_surgery_projections/{caseId}/… and returns
 * checksum + storage path. A .stub path is never produced.
 */

import { findUnsafeProjectionLabel } from "./safety";
import { deriveProjectionModeAllocation, STANDARD_PRE_SURGERY_PROJECTION_ASSUMPTIONS } from "./modes";
import type { PreSurgeryProjectionProvider, PreSurgeryProjectionInput, PreSurgeryProjectionResult } from "./provider";
import { composeLocalIllustrativeProjection } from "./localIllustrativeComposer";

export const LOCAL_ILLUSTRATIVE_PROVIDER_ID = "local-illustrative-v1" as const;
export const LOCAL_ILLUSTRATIVE_MODEL_VERSION = "local-illustrative-v1" as const;

export type LocalIllustrativeStorageDeps = {
  /** Resolve sourceImageRef (storage:path or image:id) to image bytes. */
  loadSourceBytes: (sourceImageRef: string) => Promise<Buffer>;
  /** Persist generated bytes; must create a real storage object. */
  storeOutput: (storagePath: string, bytes: Buffer, contentType: string) => Promise<void>;
};

export type LocalIllustrativeGenerateMeta = {
  mimeType: "image/jpeg";
  fileSizeBytes: number;
  widthPx: number;
  heightPx: number;
};

export type PreSurgeryProjectionResultWithAssetMeta = Extract<PreSurgeryProjectionResult, { ok: true }> & {
  mimeType?: string;
  fileSizeBytes?: number;
  widthPx?: number;
  heightPx?: number;
};

export function buildLocalIllustrativeStoragePath(input: {
  caseId: string;
  mode: string;
  outputChecksum: string;
  extension?: string;
}): string {
  const ext = input.extension ?? "jpg";
  return `pre_surgery_projections/${input.caseId}/${input.mode}/${input.outputChecksum.slice(0, 16)}.${ext}`;
}

export function createLocalIllustrativePreSurgeryProjectionProvider(
  deps: LocalIllustrativeStorageDeps
): PreSurgeryProjectionProvider {
  return {
    async generateProjection(input: PreSurgeryProjectionInput): Promise<PreSurgeryProjectionResult> {
      const allocation = deriveProjectionModeAllocation(input.approvedGraftPlan, input.mode);
      const labelViolation = findUnsafeProjectionLabel(allocation.patientSafeLabel);
      if (labelViolation) {
        return { ok: false, errorCode: labelViolation.code, message: labelViolation.message };
      }

      let sourceBytes: Buffer;
      try {
        sourceBytes = await deps.loadSourceBytes(input.sourceImageRef);
      } catch (e) {
        return {
          ok: false,
          errorCode: "source_image_unavailable",
          message: e instanceof Error ? e.message : "Could not load source image for projection",
          retryable: true,
        };
      }

      if (!sourceBytes || sourceBytes.byteLength === 0) {
        return {
          ok: false,
          errorCode: "source_image_empty",
          message: "Source image bytes are empty",
          retryable: false,
        };
      }

      try {
        const composed = await composeLocalIllustrativeProjection({
          sourceBytes,
          caseId: input.caseId,
          mode: input.mode,
          plan: input.approvedGraftPlan,
          annotations: input.approvedAnnotations,
          engineVersion: String(input.engineVersion),
          inputChecksum: input.inputChecksum ?? "pending",
        });

        const outputStorageRef = buildLocalIllustrativeStoragePath({
          caseId: input.caseId,
          mode: input.mode,
          outputChecksum: composed.outputChecksum,
          extension: composed.extension,
        });

        await deps.storeOutput(outputStorageRef, composed.bytes, composed.mimeType);

        const result: PreSurgeryProjectionResultWithAssetMeta = {
          ok: true,
          outputStorageRef,
          outputChecksum: composed.outputChecksum,
          limitations: [
            "Illustrative planning aid — not a guaranteed outcome.",
            "Local illustrative composer overlays approved plan zones on the source photograph.",
            "Does not predict graft survival, calibre, curl, or colour.",
            "Facial identity and anatomy outside approved recipient zones must remain unchanged.",
            ...input.patientSafeProjectionConstraints,
          ],
          planningAssumptions: [...STANDARD_PRE_SURGERY_PROJECTION_ASSUMPTIONS],
          mode: input.mode,
          modelVersion: LOCAL_ILLUSTRATIVE_MODEL_VERSION,
          mimeType: composed.mimeType,
          fileSizeBytes: composed.bytes.byteLength,
          widthPx: composed.widthPx,
          heightPx: composed.heightPx,
        };
        return result;
      } catch (e) {
        return {
          ok: false,
          errorCode: "local_illustrative_compose_failed",
          message: e instanceof Error ? e.message : "Local illustrative composition failed",
          retryable: true,
        };
      }
    },

    async healthcheck() {
      const started = Date.now();
      return {
        healthy: true,
        detail: "local-illustrative-v1 storage-bound composer ready",
        latencyMs: Date.now() - started,
      };
    },
  };
}
