import { DOCTOR_PHOTO_CATEGORIES } from "@/lib/doctorPhotoCategories";

export type AuditWorkflowFieldMetadata = {
  isCaseStable: boolean;
  isDefaultable: boolean;
  isFollowupOnly: boolean;
  canInheritFromOriginalCase: boolean;
  canPrefillFromDoctorDefault: boolean;
  canPrefillFromClinicDefault: boolean;
  lockAfterInitialSurgerySave: boolean;
};

const FOLLOWUP_EVIDENCE_KEYS = DOCTOR_PHOTO_CATEGORIES
  .map((category) => category.key)
  .filter((key) => key.startsWith("img_followup_") || key === "img_trichoscopy");

// Copied forward from original surgery for follow-up audits.
export const caseStableFields = [
  "submission_type",
  "audit_type",
  "case_id",
  "clinic_name",
  "clinic_branch",
  "doctor_name",
  "country_jurisdiction",
  "surgery_date",
  "multi_day_flag",
  "procedure_day_breakdown",
  "previous_surgery_history",
  "previous_surgery_details",
  "repair_case_flag",
  "procedure_type",
  "primary_procedure_type",
  "areas_treated",
  "primary_area_treated",
  "hairline_lowering_flag",
  "crown_included_flag",
  "beard_donor_used",
  "body_donor_used",
  "patient_age_bracket",
  "patient_sex",
  "ethnicity_hair_background",
  "hair_type_curl_pattern",
  "hair_calibre_category",
  "hair_shaft_diameter_microns",
  "hair_colour",
  "skin_hair_contrast",
  "primary_diagnosis",
  "secondary_diagnosis",
  "hair_loss_scale_used",
  "hair_loss_grade",
  "hair_loss_stability",
  "miniaturisation_present",
  "miniaturisation_regions",
  "dupa_retrograde_flag",
  "scalp_condition_flags",
  "planned_graft_count",
  "actual_graft_count",
  "estimated_hair_count",
  "zones_planned",
  "density_goal_by_zone",
  "hairline_design_strategy",
  "future_loss_planning",
  "risk_counselling_documented",
  "candidate_suitability_rating",
  "donor_quality_rating",
  "donor_density_rating",
  "estimated_donor_capacity",
  "estimated_donor_capacity_numeric",
  "safe_donor_zone_assessed",
  "donor_scarring_present",
  "donor_density_per_cm2",
  "avg_hairs_per_graft",
  "overharvesting_risk_flag",
  "overharvesting_signs",
  "donor_mapping_notes",
  "extraction_method",
  "extraction_devices_used",
  "primary_extraction_device",
  "extraction_technique",
  "extraction_operator",
  "extraction_experience_years",
  "punch_sizes_used",
  "primary_punch_size",
  "punch_types_used",
  "primary_punch_type",
  "punch_manufacturers_used",
  "punch_motion",
  "motor_speed_rpm",
  "extraction_device_change_notes",
  "punch_size_change_notes",
  "punch_type_change_notes",
  "reason_for_intraoperative_changes",
  "transection_category",
  "transection_rate_percent",
  "buried_graft_rate_percent",
  "extraction_time_minutes",
  "holding_solutions_used",
  "primary_holding_solution",
  "temperature_controlled_storage",
  "grafts_kept_hydrated",
  "sorting_performed",
  "holding_solution_notes",
  "graft_handling_team_notes",
  "microscopic_inspection_used",
  "graft_composition_available",
  "out_of_body_time_category",
  "recipient_sites_created_by",
  "site_creation_method",
  "slit_orientation",
  "site_instrument_sizes_used",
  "dense_packing_attempted",
  "hairline_direction_quality",
  "angle_direction_notes",
  "native_hair_protection_strategy",
  "implantation_method",
  "implantation_devices_used",
  "primary_implantation_device",
  "implanted_by",
  "implantation_time_minutes",
  "singles_reserved_for_hairline",
  "implantation_device_notes",
  "popping_issues_observed",
  "implant_depth_consistency",
  "intraoperative_adjuncts_used",
  "intraop_prp_used",
  "intraop_exosomes_used",
  "exosome_type",
  "partial_transection_used",
  "intraop_adjunct_notes",
  "postoperative_treatments_included",
  "postoperative_treatments_recommended",
  "finasteride_recommended",
  "minoxidil_recommended",
  "follow_up_plan_documented",
  "donor_recovery_protocol_included",
  "postoperative_protocol_notes",
  "graft_tray_quality_rating",
  "graft_sorting_method",
  "visible_transection_on_tray",
  "graft_tissue_quality_concern",
  "microscopic_graft_review_available",
] as const;

// Prefilled from saved doctor defaults for new audits and still editable per case.
export const doctorDefaultFields = [
  "requested_by",
  "review_purpose",
  "additional_operators",
  "additional_operators_details",
  "future_loss_planning",
  "risk_counselling_documented",
  "candidate_suitability_rating",
  "extraction_method",
  "extraction_devices_used",
  "primary_extraction_device",
  "extraction_technique",
  "extraction_operator",
  "punch_sizes_used",
  "primary_punch_size",
  "punch_types_used",
  "primary_punch_type",
  "punch_manufacturers_used",
  "punch_motion",
  "motor_speed_rpm",
  "holding_solutions_used",
  "primary_holding_solution",
  "temperature_controlled_storage",
  "grafts_kept_hydrated",
  "sorting_performed",
  "holding_solution_notes",
  "recipient_sites_created_by",
  "site_creation_method",
  "slit_orientation",
  "site_instrument_sizes_used",
  "dense_packing_attempted",
  "implantation_method",
  "implantation_devices_used",
  "primary_implantation_device",
  "implanted_by",
  "singles_reserved_for_hairline",
  "implantation_device_notes",
  "intraoperative_adjuncts_used",
  "intraop_prp_used",
  "intraop_exosomes_used",
  "exosome_type",
  "partial_transection_used",
  "intraop_adjunct_notes",
  "postoperative_treatments_included",
  "postoperative_treatments_recommended",
  "finasteride_recommended",
  "minoxidil_recommended",
  "follow_up_plan_documented",
  "donor_recovery_protocol_included",
  "postoperative_protocol_notes",
] as const;

// Prefilled from saved clinic protocol defaults for new audits and still editable per case.
export const clinicDefaultFields = [
  "requested_by",
  "review_purpose",
  "clinic_branch",
  "additional_operators",
  "additional_operators_details",
  "future_loss_planning",
  "risk_counselling_documented",
  "candidate_suitability_rating",
  "extraction_method",
  "extraction_devices_used",
  "primary_extraction_device",
  "extraction_technique",
  "extraction_operator",
  "punch_sizes_used",
  "primary_punch_size",
  "punch_types_used",
  "primary_punch_type",
  "punch_manufacturers_used",
  "punch_motion",
  "motor_speed_rpm",
  "holding_solutions_used",
  "primary_holding_solution",
  "temperature_controlled_storage",
  "grafts_kept_hydrated",
  "sorting_performed",
  "holding_solution_notes",
  "recipient_sites_created_by",
  "site_creation_method",
  "slit_orientation",
  "site_instrument_sizes_used",
  "dense_packing_attempted",
  "implantation_method",
  "implantation_devices_used",
  "primary_implantation_device",
  "implanted_by",
  "singles_reserved_for_hairline",
  "implantation_device_notes",
  "intraoperative_adjuncts_used",
  "intraop_prp_used",
  "intraop_exosomes_used",
  "exosome_type",
  "partial_transection_used",
  "intraop_adjunct_notes",
  "postoperative_treatments_included",
  "postoperative_treatments_recommended",
  "finasteride_recommended",
  "minoxidil_recommended",
  "follow_up_plan_documented",
  "donor_recovery_protocol_included",
  "postoperative_protocol_notes",
] as const;

// Always completed fresh on each follow-up review.
export const followupOnlyFields = [
  "outcome_audit_stage",
  "growth_outcome_category",
  "donor_healing_category",
  "patient_satisfaction_category",
  "corrective_surgery_likely",
  "outcome_notes",
  "review_concern_categories",
  "claimed_evidenced_discrepancy",
  "incomplete_records_flag",
  "case_complexity_rating",
  "auditor_confidence_level",
  "forensic_notes",
  ...FOLLOWUP_EVIDENCE_KEYS,
] as const;

const caseStableSet = new Set<string>(caseStableFields);
const doctorDefaultSet = new Set<string>(doctorDefaultFields);
const clinicDefaultSet = new Set<string>(clinicDefaultFields);
const followupOnlySet = new Set<string>(followupOnlyFields);
const allWorkflowFields = new Set<string>([
  ...caseStableSet,
  ...doctorDefaultSet,
  ...clinicDefaultSet,
  ...followupOnlySet,
]);

export const auditWorkflowFieldMetadata: Record<string, AuditWorkflowFieldMetadata> = Object.fromEntries(
  Array.from(allWorkflowFields).map((fieldKey) => [
    fieldKey,
    {
      isCaseStable: caseStableSet.has(fieldKey),
      isDefaultable: doctorDefaultSet.has(fieldKey) || clinicDefaultSet.has(fieldKey),
      isFollowupOnly: followupOnlySet.has(fieldKey),
      canInheritFromOriginalCase: caseStableSet.has(fieldKey),
      canPrefillFromDoctorDefault: doctorDefaultSet.has(fieldKey),
      canPrefillFromClinicDefault: clinicDefaultSet.has(fieldKey),
      lockAfterInitialSurgerySave: caseStableSet.has(fieldKey),
    },
  ])
);

export const AUDIT_WORKFLOW_UX_COPY = {
  useSavedDefaults: "Use saved defaults",
  copyFromPreviousCase: "Copy from previous case",
  inheritedFromOriginalSurgeryRecord: "Inherited from original surgery record",
  onlyUpdateWhatChanged: "Only update what changed",
  addAdvancedDataToImproveConfidenceAndBenchmarking:
    "Add advanced data to improve confidence and benchmarking",
} as const;
